### ISSUE TITLE
macOS UI: allow multi-select

### ISSUE THREAD

**Issue by marcelstoer** [mmcguill/Strongbox#101]
Request: allow to multi-select records using the shift / cmd keys.

**Comment by mmcguill** [comment]
Sounds good, you would want multi select for operations like moving/deleting I assume, or did you have something else in mind?

**Comment by marcelstoer** [comment]
Indeed, I had wanted to move multiple records to a folder.

**Comment by mmcguill** [comment]
Available now for delete/move in 1.7.1
