### ISSUE TITLE
macOS UI: improvement to "new database" dialog

### ISSUE THREAD

**Issue by marcelstoer** [mmcguill/Strongbox#103]
Just a nit pick...

<img width="498" alt="Screenshot 2019-04-28 at 14 50 11" src="https://user-images.githubusercontent.com/624195/56865086-3b41f780-69ca-11e9-8357-6c3ab83faa58.png">

**Comment by mmcguill** [comment]
Fair :)

**Comment by mmcguill** [comment]
Fixed in 1.7.1
