### ISSUE TITLE
macOS UI: show all custom fields in quick view

### ISSUE THREAD

**Issue by marcelstoer** [mmcguill/Strongbox#104]
Accessing a custom field for copy-pasting is currently rather cumbersome:
- open Item Details
- switch to Custom Fields tab
- double click the item
- select the value field
- copy value

If the custom fields were in present in the quick view I could simply click the copy icon. Sweet.

**Comment by mmcguill** [comment]
Yes, this is possible... they were in there before the release of the "new" UI, but some found it a little crowded... Could probably put them in as an configurable option.

**Comment by georgesnow** [comment]
what about a right click option for custom fields? so if the entry has custom fields and you right click that items it shows the custom Fields Title and an option to copy. other KeePAss variants do this.

**Comment by mmcguill** [comment]
Yes, this sounds good. Would that work for you @marcelstoer ?

**Comment by marcelstoer** [comment]
I work with the quick view panel shown - always. Hence, displaying them there would be by far the quickest, most convenient way. Nothing beats clicking a record in the list and seeing all fields on the right.

**Comment by mmcguill** [comment]
Probably nice to have both...

**Comment by mmcguill** [comment]
Available now in 1.7.1.
