### ISSUE TITLE
macOS UI: necessary to protect empty field?

### ISSUE THREAD

**Issue by marcelstoer** [mmcguill/Strongbox#105]
I find it irritating the empty password fields are still marked with 8 *. I was wondering whether that be a security feature but I don't see good reasons why it should be.

**Comment by mmcguill** [comment]
Not done for any particular reason, just the default is to mask.... Any particular use case for an empty password and wanting it to be visible as such if empty?

**Comment by marcelstoer** [comment]
I keep records that are not of the typical webform-username-password type. Hence, not all my records _need_ a password.

**Comment by mmcguill** [comment]
Ok, the issue seems pretty cosmetic and I'm not sure how other users would feel about exposing an empty password like this... will leave open for comment. Perhaps a configuration option for this is best.

**Comment by marcelstoer** [comment]
If everything non-cosmetic works as expected only the cosmetic issues remain 😄Nice job!

**Comment by mmcguill** [comment]
Haha, thanks! 😁

**Comment by shad0whawk** [comment]
I also have entries with no passwords—either on, off or a setting works for me. I like settings because they provide the user with flexible options, but you may end up with a very long settings menu.

**Comment by mmcguill** [comment]
This is optional now with 1.7.1. Feel free to reopen if there are any issues.
