### ISSUE TITLE
iOS: Keyfile and TouchID

### ISSUE THREAD

**Issue by georgesnow** [mmcguill/Strongbox#107]
not sure if this is an issue or user error....

i had attempted to add a keyfile to a current database stored iCloud. I added it on my mac KeePass client and saved the database. I went to my iOS device selecting the database (settings were set to Read Only) and failed. makes sense cause it now needs a keyfile. so i selected advanced option. picked the Keyfile stored in the local folder for Strongbox on my iPhone. entered the password database unlocked. Settings show the database is set up for TouchID. exit out and re-select database and it asks me for password. so i do the same process again and same thing. 

is this the intended behavior if you have keyfile? 

I went back to my mac removed the keyfile and made it password only. did the same thing again and toggled read only and touchID off and back on. exited the database and touchId now unlocks the database. Should I have done the same thing with the keyfile and toggle the Read only and Touch ID?

**Comment by mmcguill** [comment]
Hmmm, I think what should happen here when the Convenience Unlock (Biometric and/or PIN) fails is:

1. Disable any existing convenience methods (as the stored info is now invalid)
2. Ask/Prompt to use Convenience method on next successful open.

Sound right?

**Comment by georgesnow** [comment]
Yup ok

**Comment by mmcguill** [comment]
@georgesnow This should be fixed now with 1.29.0... Please re-open or open another issue if you have any trouble
