### ISSUE TITLE
AutoFill QuickType Matching Question/Issue

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#108]
I have a large number of entries that are specific to my company that contain companyname.org either in the URL or the notes field.  If I land on a company website that requires a login and select the key icon to show all of the relevant matches in Strongbox, I'm scrolling through a long list of items before I find what I need which usually ends up being at the bottom.  This occurs because they all contain companyname.org in the entry.  I know initially QuickType was more limited in matching which has it's cons.  Is it possible to add a setting to set the  matching by either companyname.org or more precisely site.companyname.org?  Essentially I'd like to be able to adjust the preciseness depending on which method works better for me.  Just curious if that's possible...

As always thanks for all of your hard work and effort!

**Comment by georgesnow** [comment]
Are you finding that the preferred entry quicktype shows isn’t the right one? I have similar situation but my experience has been the closer match works. So it I have entry for mail.work.com and www.work.com(uses different passwords) and I go to the mail.work.com site QuickType presents  that entry as the “preferred” or first option

**Comment by shad0whawk** [comment]
It’s probably an issue specific to me with this specific website combined with the entries in my database. For one website, it shows me a list of roughly 60-80 matching entries because they have company name.org in them. I just noticed that the URL on the website is different than the entry URL because the website directed me to the mobile site so it’s not finding a direct match in my database and presenting everything related. I’m probably going to close this since it’s not really QuickTypes fault.
