### ISSUE TITLE
Convenience PIN UI Logic Flow

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#109]
If I select Turn Convenience PIN on and then press Cancel, a dialog box appears stating the PINs don’t match which seems odd if I’m choosing to cancel it. The operation should cancel without displaying this dialog box.

**Comment by mmcguill** [comment]
Yes, confirmed. Nice spot.

**Comment by mmcguill** [comment]
Should be fixed with 1.27.2

**Comment by shad0whawk** [comment]
Unfortunately this issue still exists in 1.27.2

**Comment by mmcguill** [comment]
@shad0whawk should be fixed now with 1.28.0. Will leave open for you to verify and close...

**Comment by shad0whawk** [comment]
Looks like it's fixed :-) Thanks!
