### ISSUE TITLE
Cannot open document

### ISSUE THREAD

**Issue by nicojaure** [mmcguill/StrongBox#11]
Hi guys

I've been using IOS solution. 
Now I want to open the same file I've been using on mobile on my mac with the new desktop app.
I'm getting the error "The document “XXXX.psafe” could not be opened. Strongbox cannot open files in the “Document” format."

¿Can you help me?

Thx
Nico

**Comment by mmcguill** [comment]
Hi @nicojaure, Sounds like there's something wrong with that file, how are you hosting it? Is it on Google Drive? Usually the extension is '.psafe3'. Are you using the App from the App Store or built from Source here?
