### ISSUE TITLE
iOS: Database Saving - Two Stage Edit & Then Commit

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#110]
I’m curious about the current implementation of the save database functionality. Currently it saves every time I make a change to an entry which normally is okay, but my database resides on OneDrive so each time it is saved it has to be uploaded. Is there a way to make the save operation work like the Keepass desktop program where multiple changes can be made and then saved manually by selecting “save” or upon exit (enabled by a setting)?

**Comment by mmcguill** [comment]
Hi @shad0whawk, 

The new UI on the Details screen should allow to make multiple changes before committing them which should help here. 

Similarly the Browse Screen allows bulk moves and deletes.

Outside of this, if might be a little more difficult UI wise to manage multiple changes and then a commit... Maybe if you could give an example of how you would see this working it would help.

-Mark

**Comment by shad0whawk** [comment]
I believe the current implementation saves at the entry level after changes are made within the entry and the user selects "Done".  So if I change 20 entries, that's 20 saves back to OneDrive. It would be nice to be able to make changes to 20 entries and then save it once at the database level if desired or abort the changes.  I understand if it's not technically possible or creates too much work. I just thought I'd float the idea if it was easily possible.

**Comment by georgesnow** [comment]
this is sort of analogous to auto-save and in @shad0whawk case it sounds like auto save would be turned off. And would be required to manually save. only downside if the app crashes or unexpectedly closes whatever any changes would be lost

**Comment by mmcguill** [comment]
Understood. It might be nice to have this alright... it's just to find a way to enable something like this without getting in the way of the 90% - quick edit use case...

**Comment by shad0whawk** [comment]
Thanks for discussing the idea.  I understand if it’s challenging and not feasible to do given the existing implementation. It’s not a deal breaker by any means. I was more curious than anything.

**Comment by mmcguill** [comment]
For sure, the real challenge seems to me to be the UI for something like this.

**Comment by shad0whawk** [comment]
I’ll close this since it’s not a practical request at this time.
