### ISSUE TITLE
iOS: Request - Allow Copying of Details from Notes Section - .kdbx files

### ISSUE THREAD

**Issue by dvVjNaV8xwo6** [mmcguill/Strongbox#111]
I am a KeePassXC user, thus I am referring to a .kdbx database file when using the Strongbox interface for iOS.  I do not know if this would be present in other database file types but I assume it would be similar.

Current Behavior:
Database is open > Specific entry is open > Touching NOTES section copies entire notes section

Desired Behavior:
Database is open > Specific entry is open > Touching NOTES section allows you to highlight specific text to copy within notes section rather than entire section.

I often keep information related to an account such as a secret question & answer in the notes section of my entry, along with various other information.  It creates some extra steps when the entire notes section is copied.

Perhaps I am missing something obvious here to disable/modify this behavior, if so please let me know.

Thank you for the attention to this project.

**Comment by shad0whawk** [comment]
I opened this exact same issue a few minutes ago and then realized version 1.27.2 now allows this behavior again. I saw it in the release notes and tested it.

**Comment by mmcguill** [comment]
As @shad0whawk says, this should be working for you in 1.27.2 now. Double Tap to Copy All, or select individual portions
