### ISSUE TITLE
iOS: can‘t create database in iCloud

### ISSUE THREAD

**Issue by limuc** [mmcguill/Strongbox#112]
Hi,
i have the following problem: i had my database in the Strongbox-Folder in iCloud. Then i deleted my whole iCloud data. Now when i try to create a database in iCloud (type/name doesn‘t matter, tried everything) i get „Error Saving Database - Failed to create file“. I tried migrating local to iCloud, doesn‘t work either. I also tried to reinstall the app and different devices.
Seems like the problem is that the iCloud folder (the one with the Strongbox icon) can not be created.

![587C5F5D-710F-4828-A08F-D609EB284354](https://user-images.githubusercontent.com/49267156/57522165-4548ec00-7322-11e9-825c-696736f37dbd.jpeg)

**Comment by mmcguill** [comment]
Hi @limuc 

Any further news on this? 

Could you try Signing out and back into iCloud and also switching iCloud On/Off in Strongbox preferences?

**Comment by limuc** [comment]
Hi @mmcguill 

Unfortunately not, tried the "switching iCloud On/Off in Strongbox preferences", didn't help. I would like to avoid logging out and back in iCloud, because then i would have to redownload my large iCloud Photos library and my connection isn't that fast.

At the moment im just using another cloud storage provider, so it's not a big problem.

**Comment by mmcguill** [comment]
Ok @limuc. Have you tried uninstalling/reinstalling Strongbox? 

Or manually creating the Strongbox folder in your iCloud Drive?

**Comment by limuc** [comment]
Yes @mmcguill 
The former multiple times (on two devices) and i also created a folder but it didn't work and didn't get the symbol (like the app folders normally do).

**Comment by mmcguill** [comment]
Hi @limuc, I think I'll have to try to recreate the problem myself. Can you tell me how you "deleted my whole iCloud data"? I'll probably do the same

**Comment by limuc** [comment]
Yes of course. I just marked all folders and deleted them. I just did it in the Files-app on my iPad. Then i emptied the trash.

**Comment by limuc** [comment]
Yesterday i experienced another weird glitch with my iCloud Drive, so today i contacted the Apple support and indeed there was something wrong on their end. They fixed it and Strongbox lets me save in the iCloud again. So i will close this issue now. Thanks for looking into it!

**Comment by mmcguill** [comment]
Glad to hear this is sorted for you, it would have been a difficult one to figure out...
