### ISSUE TITLE
Inconsistencies in UI Elements Size

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#115]
Thanks for continuing to work on the new iOS UI. It’s looking good and I really like it. I wanted to point out a few areas that appear inconsistent with the new format. 

1.  I noticed you updated the Autofill entry details list to match the new, smaller format, but the Autofill database menu list still uses the larger size view. The main Strongbox database menu list uses the new format so I wanted to point out the inconsistency between the two. 

2.  The History submenu that displays the historical item entries still uses the old, larger format. It’s noticeable because the text is bigger and the icons are noticeably bigger than the icons on the previous two screens in the process flow. 

I’ll post again if I see anything else that looks out of place.

**Comment by mmcguill** [comment]
Hi @shad0whawk - I believe both of these issues are fixed with 1.29.0. Could you verify and close if ok?

**Comment by shad0whawk** [comment]
Item 2 looks good and is consistent with the rest of the UI. Item 1–the database list in AutoFill—still uses the larger view if I pull it up in Safari.

**Comment by mmcguill** [comment]
Just so we're clear, would you mind sending a screen shot of the screen you're talking about in 1) Feel free to blur/redact text.

**Comment by shad0whawk** [comment]
![C4A2211A-DB55-4E5D-A839-5E7C057A246D](https://user-images.githubusercontent.com/6074105/58508383-284d4f00-8151-11e9-9f5e-3a1eeb1c4375.jpeg)

I was referring to this window in the AutoFill process where you initially select the database.  The UI elements are significantly larger than those on the remainder of the program since you’ve been updating the UI (which looks very good BTW).  This is from my iPad but the iPhone layout is the same.  Does that help?

**Comment by mmcguill** [comment]
AutoFill:
![image](https://user-images.githubusercontent.com/344791/58508976-b814ec80-8195-11e9-8b5a-75108b92c2cc.png)

Regular App:
![image](https://user-images.githubusercontent.com/344791/58508993-c3681800-8195-11e9-9623-7754d8c1ed34.png)

Definitely a slight difference alright. Thanks @shad0whawk - I'll get this fixed up

**Comment by shad0whawk** [comment]
As always, thanks!

Marc Burris
303.809.8149
marc.burris@gmail.com

________________________________

**Comment by shad0whawk** [comment]
Looks good! Closing...
