### ISSUE TITLE
Reopening Issue 88 (Bug Still not Fixed)

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#116]
Hmm this issue is still not fixed for me in 1.27.2 and is super easy to accidentally invoke. Theres two ways to create the issue. (1) Place an entry into edit mode by swiping left. There’s about a one-second delay after tapping somewhere else on the screen before the “Cancel” button disappears. Swiping left on any other entry in that one second window makes the “Cancel” button permanent and disallows the user to go back a screen.  (2) The same happens if an entry is in edit mode and you swipe left on another entry to put it into edit mode.

 Can you reopen the issue?

**Comment by mmcguill** [comment]
Reopened #88
