### ISSUE TITLE
Modification / Creation Date Interpretation Bug

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#117]
I have a Keepass2 database that I've opened with Strongbox and both the creation and modification dates are being read incorrectly by Strongbox.  The dates shown in Strongbox appear to be behind by two full days, but the time component is spot on.  This appears to impact all entries in the database.  If I modify an entry, the modification date is set to today in Strongbox, but two full days in the future if I open the database in Keepass2.  I noticed the issue first in Keepass when I looked at an entry I updated yesterday and was surprised to see the modification set to tomorrow.  I use the advanced synchronization features of Keepass2 so this could cause issues with data loss.

What's interesting is that the Strongbox desktop app, the Macpass desktop app, and another iOS Keepass app show the same incorrect dates as the Strongbox iOS app with a two day difference.  If I open it with the KeepassXC desktop app, it shows the correct dates same as Keepass2.

**Comment by mmcguill** [comment]
Ok, strange, thanks for the report @shad0whawk... will look into this shortly

**Comment by shad0whawk** [comment]
I have some more information for you on this issue.  I created a set of new databases and tested the different encryption methods.  It seems to be directly related to using Argon for the key derivation method.  It doesn't happen when using AES or ChaCha encryption method and/or the AES key derivation method. I can consistently reproduce the issue.  Unfortunately, I don't know the "why" behind it.

**Comment by shad0whawk** [comment]
Another interesting observation in my testing.  The testing for my previous comment was conducted on two newly created databases—one Argon and one AES.  On the Argon database, I was able to change the encryption method to AES, resolve the issue with how the dates are read, change it back to Argon, and recreate the issue.  The interesting part occurred when I tried switching the encryption on my primary database from Argon to AES and it failed to resolve this issue.  I was hoping that switching back to AES would be an interim solution until this was figured out—I guess not.

**Comment by shad0whawk** [comment]
I sent this information to another developer with the same issue and this was the response, “The reason is in different way of storing timestamps in kdbx3 (AES) and newer kdbx4 format (Argon2). In the former, they are stored as human-readable text. The new format, in turn, has switched to a more machine-oriented “seconds since 1 Jan 0001 midnight”.  I hope that helps in identifying and fixing the issue.

**Comment by keepassium** [comment]
I had to run Xcode and VStudio side-by-side to figure it out... It seems .NET and Foundation calculate time differently. Specifically, the number of seconds between 0001-01-01 00:00:00 (.NET reference date) and 2001-01-01 00:00:00 (Foundation reference date) is:
- 63114076800 (according to Apple) 
- 63113904000 (according to Microsoft)
Exactly 48 hours difference.

**Comment by mmcguill** [comment]
Wow, super interesting. Thanks for the help and the pointers. I'll try get a fix in for this in the next release.

**Comment by shad0whawk** [comment]
Appears to be fixed! Thanks for getting to it so quickly!  As always, much appreciated!  Closing...
