### ISSUE TITLE
Make convenience password optional to enable duress password

### ISSUE THREAD

**Issue by pixel8383** [mmcguill/Strongbox#123]
Using TouchID or FaceID togheter with a convenience password could represent another unlock way to the database for the attacker.
If the attacker is able to bypass Touch/FaceID somehow having only a duress password could trick the attacker to have a try "the easier way" (replicate Touch/FaceID is not that easy).
Nobody except the owner knows if the app is configured with a convenience password or a duress password. This way, one try would lead to the loosing of the access to the master password which represent the last step to open the database.

I would just change in the settings the ability to enable a duress password without setting up a convenience one.

**Comment by mmcguill** [comment]
Ok, interesting, I'm not sure I fully get how it would work or the benefit. Thoughts @shad0whawk?

**Comment by shad0whawk** [comment]
So if I understand what the OP is requesting, he wants to be able to enable a duress PIN without having to enable a convenience PIN and somehow conditionally prompt for the duress PIN but skip the convenience PIN when he does a normal unlock.  Interesting concept but I don't see how that's doable since you have to set a convenience PIN to enable the PIN functionality.  Otherwise, how would the program know when to conditionally prompt for a duress PIN?  I don't see you being able to set one without the other and optionally require the duress PIN but not the convenience PIN.  I can think of a few ways, but they don't make sense from a security standpoint.  Just my thoughts since you asked...

**Comment by pixel8383** [comment]
My idea is: I don't need a convenience PIN. I am ok in using only a biometric access (Touch/Face ID) so the software could prompt a duress PIN useful to immediately delete the database master password if inserted. The setup is obviously known only by the owner of the phone and this could immediately avoid any further try to break into the database.

If/when the biometric access doesn't work, the owner can just trigger the duress PIN and access to the databases which will request once again the master password to be loaded.

**Comment by mmcguill** [comment]
Could you give more detail on what you this looks like when you say "The software could prompt a Duress PIN"? How would it know when to do this?

I'm still not clear on the requirement here. Thanks.

**Comment by pixel8383** [comment]
Well... by my point of view you should only be able to enable a duress (let's call it "fake") PIN. You don't need to setup it, just enable this function. Then you can login with your biometrics and you are prompt with a numbers keyboard to insert a PIN. The owner knows to alaways avoid to insert any PIN there. In case an attacker tries any PIN, the master password of the database will be deleted (an additional option could be to give 2 or more retry times before doing it to avoid wrong clicking by the owner).

**Comment by mmcguill** [comment]
So I am right in saying that an attacker would have to successfully biometrically authenticate before this "fake" PIN screen would appear?

**Comment by pixel8383** [comment]
For sure he should be able to login on your iPhone. But we don't know if the attacker knows the iPhone password (or is so sophisticated to be able to bypass/emulate the biometrics).
In any case, when the attacker opens StrongBox is prompted with a keypad for a PIN AND the ability to use biometrics.
Here happens the trick: if the function is enabled, the attacker could be tempted to try with a numerical password first. But any attempt to insert a number there would result to delete the master password of every db stored inside the app.
Another way could be: the attacker can open Strongbox because no authentication is required to open the app but the trick is enabled for some databases. In that case, only the involved database would get the password to be deleted from iOS keychain.
Maybe my first attempt to describe the idea was not so accurate (as I can see the title is misleading now) but I hope now it's more clear.

**Comment by mmcguill** [comment]
Ok, I think I sort of get what you mean, though I think perhaps the existing 'App Lock' -> Delete All Data functionality sort of has you covered here. I'm not sure if there's much extra value in adding a more complicated configuration for this functionality, or being able to change this setting on a per database basis. 

Any feedback others have on this is welcome

**Comment by shad0whawk** [comment]
My two cents...

I’d agree with @mmcguill—seems a bit unnecessary to add another optional layer of complexity. I think the existing configuration options have 99% of users covered. The programming investment probably isn’t worth the return.

**Comment by mmcguill** [comment]
I'm going to close this one, I don't think the requirement is super well defined, there are other ways of achieving the desired results (I believe) and I think it would complicate the flow unnecessarily. Thanks for the discussion guys.
