### ISSUE TITLE
Offer Offline Cache Fallback in case of any issue opening with Cloud Storage Providers

### ISSUE THREAD

**Issue by mmcguill** [mmcguill/StrongBox#13]
It would be useful to allow this offline cache fallback in cases other than being fully offline, e.g. cloud provider issues, bad connectivity etc.

**Comment by mmcguill** [comment]
This should be good with 1.18.1.

Thanks.
-Mark

**Comment by Ben-Voris** [comment]
When I use the password extension I see the last cache update time for my Google drive safes. Can I see this elsewhere?

**Comment by mmcguill** [comment]
Hi Ben,

This isn't exposed in the UI at the moment, but I'll create an issue to expose this on the Safe Settings screen. 

Cheers,
-Mark

**Comment by Ben-Voris** [comment]
Thanks. I only use enterprise GitHub, which doesn’t support smiley faces and such (reactions?), so I really don’t know how those work. But, fwiw, I gave this issue a thumbs up. As I did that, I thought I should take a few more seconds to say how much I appreciate the high quality of support that you provide for Stongbox. Though I know nothing about iOS development, I do have a bit of experience at what it takes to write stable code and to be responsive users. You do this well, and I appreciate that. Thank you. 

It’s a pleasure to recommend Strongbox, without qualm, to my colleagues and friends.

**Comment by mmcguill** [comment]
Thanks Ben! Really appreciate the kind words!

**Comment by idobrusin** [comment]
I faced exactly this issue today, where I wanted to access my password safe synced via Dropbox on an offline device and was surprised that I couldn't access any of my passwords.
So as mentioned previously by others, I would expect the app to cache the safe for offline usage. 

Any info about this feature beeing implemented? 



Small note: I was using KeePass Touch prior to switching to Strongbox, where caching is already implemented. Using KeePass Touch has the issue where Dropbox would create a conflicted copy of the safe in the event of two devices changing the password safe 'simultaneously'. 
I am not sure how to mitigate this issue in Strongbox, but just wanted to point out that offline caching could lead to other inconveniences down the road. Although I would prefer a conflicted copy over not having any offline access at all.

**Comment by Ben-Voris** [comment]
The Google Drive implementation caches a copy and that  copy is available both when entirely off-line and when my iPhone has been logged out of my Google account. I can’t speak to dropbox.

**Comment by mmcguill** [comment]
> I faced exactly this issue today, where I wanted to access my password safe synced via Dropbox on an offline device and was surprised that I couldn't access any of my passwords.
> So as mentioned previously by others, I would expect the app to cache the safe for offline usage.
> 
> Any info about this feature beeing implemented?
> 
> Small note: I was using KeePass Touch prior to switching to Strongbox, where caching is already implemented. Using KeePass Touch has the issue where Dropbox would create a conflicted copy of the safe in the event of two devices changing the password safe 'simultaneously'.
> I am not sure how to mitigate this issue in Strongbox, but just wanted to point out that offline caching could lead to other inconveniences down the road. Although I would prefer a conflicted copy over not having any offline access at all.

Hi @idobrusin , 

Yeah, as @Ben-Voris has already said, this is already implemented... Not sure what you were seeing there... 

If you've ever opened the Dropbox database in Strongbox (and you've not disabled offline caching) then Strongbox will create a local offline cache of that database (it will also keep it up to date as you edit etc in Strongbox). 

If Strongbox detects that you are offline or if there is an issue connecting to your Storage Provider (Dropbox) then Strongbox will offer to use the offline cache. When an offline cache is opened it is opened in Read Only mode, so there won't be any conflicts or sync issues.

Does that make sense? Did your "offline device" have an offline cache in Strongbox? You can check the status of the offline cache in the Safe settings screen.

**Comment by idobrusin** [comment]
Hi @mmcguill,
thanks for the detailed reply. It looks like it was an issue on my side, apparently my local DNS server was not resolving properly at the time of testing, resulting in my described behavior. Is there some kind of connection timeout for this case? Offline mode was not triggered, but I also didn't wait more than some seconds. 

I verified that offline mode works as you described by using flight mode and everything works as expected. My safe can be opened in offline mode just fine. 

Good idea with the read-only mode while offline. Although it makes creation of new passwords a little harder on-the-go while offline, it's the more convenient approach compared to creating conflicts. 

Thanks for your help, I really enjoy using Strongbox on a daily basis.

**Comment by mmcguill** [comment]
Hi @idobrusin, that's good to hear... yes, actually the offline detection can be a little slow to recognise the connection is bad or offline, and in particular if there was an issue with your DNS server then that could very explain why it didn't pick up being offline at all... As you've noticed, switching to airplane mode will do the trick... Thanks for the kind words, and glad you like the app! -Mark
