### ISSUE TITLE
Show Date/Time of Offline Cache on Databases List Screen

### ISSUE THREAD

**Issue by mmcguill** [mmcguill/Strongbox#130]
As mentioned in #81

**Comment by shad0whawk** [comment]
I think this functionality would be useful. I find myself occasionally wondering if I’ve opened and refreshed the database since the last edit. Typically I just reopen it, but I could see where this feature would be helpful.

**Comment by mmcguill** [comment]
Available now with 1.38.0 - Configurable (Choose the "List" icon in the Top left of the home screen)

**Comment by shad0whawk** [comment]
Thanks for implementing this in a configurable manner.  I like that I can display the last cache time—very useful.

**Comment by Slummi** [comment]
I really like the new databases list screen, especially that you removed the old quick launch screen.

**Comment by mmcguill** [comment]
Great to hear it. Glad this is working out well for you. Gonna close this one off...

**Comment by axelu** [comment]
Like it, BUT...
In the portrait view it is not visible, it is cut off and with that not readable - see attached.  Same issue actually when you get to the unlock screen in portrait mode on the line that has the Open Offline Cache toggle, it also almost completely cuts the date/time off, so one cannot actually read it. I would suggest to put it in both cases on its own line to make sure one can actually read it.  It is visible fine in landscape mode.  This is on iPhone 5s.

Landscape  

![IMG_0606](https://user-images.githubusercontent.com/1248912/62417826-1217af80-b628-11e9-96ef-50945a02a964.PNG)  

Portrait  

![IMG_0605](https://user-images.githubusercontent.com/1248912/62417827-1217af80-b628-11e9-8cce-a3950e1bd716.PNG)

**Comment by mmcguill** [comment]
hey @axelu - You can choose where to place that field. Probably best to put it in Subtitle 2 - That should work for you:

![image](https://user-images.githubusercontent.com/344791/62418035-e4793900-b61c-11e9-9616-53c5b6d135c8.png)

![image](https://user-images.githubusercontent.com/344791/62418040-f35feb80-b61c-11e9-8d89-1275d5fd3eaa.png)

Cheers,
-Mark

**Comment by axelu** [comment]
@mmcguill Got it, was not obvious to me that that is what is meant by subtitle 2.  That addresses it on the Databases List screen.  The issue that it is cut of on the Unlock screen in the Open Offline Cache toggle line remains.

**Comment by mmcguill** [comment]
Ok, to be honest I was actually thinking of removing that label completely from the Toggle Switch in Database Management since this can be seen on Home screen if desired.

**Comment by axelu** [comment]
@mmcguill Agreed.  Removing that label completely from the Toggle Switch on the Unlock screen as one option crossed my mind also, and I think that would be ok, because on - as you state correctly - can show that information on the Home screen if desired.  So I would think to remove it is better than showing something that is cut off.  Good call on the removing.

**Comment by shad0whawk** [comment]
I understand the issue in the first screen shot. That seems to be a combination of screen size, font setting and choice of what items to show where. It looks great in portrait mode on both my iPhone 8 and XS Max, but I also have my font set to the smallest setting with the cache details in subtitle 2 and file name in subtitle 1. What’s the second issue you mention with a label on a toggle switch?

**Comment by axelu** [comment]
@shad0whawk See the Open Offline Cache toggle line/row.

![IMG_0607](https://user-images.githubusercontent.com/1248912/62427347-ec3de980-b6bf-11e9-82ba-45bb837522a3.PNG)

**Comment by shad0whawk** [comment]
Ah ok I never see that screen because I have Face ID enabled. I can see it if I disable it. Mine shows up just fine when I do look at it, but again, it’s a result of my screen size plus font size.
