### ISSUE TITLE
Question about UI Changes in 1.30.0

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#131]
I think the latest round of UI changes are well thought out and help improve the overall user experience.  Two quick questions about the setting changes in the Database Management window.

(1) The previous version had a setting for "Use QuickType AutoFill" that could be toggled on/off to clear the QuickType settings and recreate the QuickType database if we had issues with this functionality.  The latest version does not include this setting.  Has this functionality been integrated in to the "Allow AutoFill Cache" setting and toggling this setting results in the same result?

(2) The previous version had a setting for "Open as Read-Only" that was migrated to the database "Unlock" window. The previous version of the program allowed the user to toggle it on/off from within the database settings.  Now the user has to go the database "Unlock" window to disable it, but that's problematic if the user has Touch/Face ID enabled on the database.  I have a database that is read-only and uses Face ID to unlock.  In order to disable read-only mode, I have to go the "Preferences" menu and disable Face ID for ALL of my databases to clear the master password so that I can change this setting on the "Unlock" window for that specific database.  I can't turn off Face ID from within the database because the "Allow Face ID Unlock" is disabled.

I hope this makes sense. If not I can elaborate further.

**Comment by mmcguill** [comment]
Hi @shad0whawk,

1) Yes integrated. Trying to tidy up/reduce the number of configs where possible. 

2) Yes, you're right, this is an oversight. I'll get that preference back in place for people in your scenario.

**Comment by shad0whawk** [comment]
Damn you’ve been busy! Nice job addressing all of these issues so quickly. Closing...

**Comment by mmcguill** [comment]
Haha yes, it's been a busy week of UI changes! Fingers crossed I haven't made things worse!
