### ISSUE TITLE
Start with TOTP

### ISSUE THREAD

**Issue by pixel8383** [mmcguill/Strongbox#132]
I like the "Start with search" setting. It helps to reach an item faster.
Similar to this, I think one nice function could be "Start with TOTP". Enabling it, the database should be opened with a view of all the TOTP records stored (a sort of Google Authenticator view).
This way, you could use the app instead of Authy/Google Authenticator when a TOTP record is needed without having to search the relative record.

**Comment by mmcguill** [comment]
I really like this idea!

**Comment by mmcguill** [comment]
This is available with 1.32.1. There is a new Browse View Preference called "View As". Here you can choose from Hierarchy, List, or TOTP List. 

If you choose TOTP List you will get a Google Authenticator style view of your entries with TOTP tokens.

**Comment by pixel8383** [comment]
Nice. I would suggest that if the TOTP list is enabled, clicking on a record will copy the TOTP value instead of the password.

**Comment by shad0whawk** [comment]
I agree with @pixel8383’s comment from a usability perspective.

**Comment by mmcguill** [comment]
So, you mean Long-Press should copy the Password? 

Currently a Tap takes you into Details/Edit mode

**Comment by shad0whawk** [comment]
I didn't think too much about it before responding to @pixel8383, but I think the current setup works fine because you can triple-tap for the TOTP code.  It's a few extra taps, but it retains the consistency across all entry types and views selections.

**Comment by pixel8383** [comment]
I am aware of keeping consistency across the app but the idea of this view was the ability to use it as TOTP manager. When you enable it, your idea is to grab the TOTP as soon as you can, not other fields.

**Comment by milesmcclane** [comment]
I agree. I have several databases, and one is purely for totp and nothing else, and will never be anything else. I think it’s fairly common to have separate password/totp databases. To be able to set up a specific totp database in this seperate manner, would be cool.

**Comment by mmcguill** [comment]
I think perhaps the best way to solve this is to allow configuration of the Tap actions. 

So you could configure on a per database basis the following:

- Tap
- Double Tap
- Triple Tap
- Long Press

to perform one of the following actions:

- Copy (Title/Username/Password/URL/Email/Notes/TOTP)
- Open Item Details (Default for Tap)

That way you can configure it how you like...

**Comment by milesmcclane** [comment]
Great idea

**Comment by shad0whawk** [comment]
Yeah that’s definitely a great idea Mark

**Comment by mmcguill** [comment]
That's cool, I'll create a separate ticket #148. Are we good to close this one off @pixel8383 ?

**Comment by pixel8383** [comment]
Yes, I think it could work. Maybe I just get used with one personalized action to retrieve the TOTP codes everywhere. Sounds good.

**Comment by mmcguill** [comment]
You'll be able to customize Tap Actions in the next release for this @pixel8383 

Closing this one off...

**Comment by pixel8383** [comment]
I have seen the implementation of the "TOTP view" function. My remarks:
1. the update/refresh of the values is not fluid. Scrolling the list make it feel like the function is not "smooth". I don't know how to describe it better, maybe it would be useful a video on this.
2. When the function is enabled, the entire database is filtered for TOTP records. My initial idea was to have the "start page" with the TOTP list records of my database but I had still to be able to explore the folders and find the other records (those with no totp value configured).

**Comment by mmcguill** [comment]
Hi @pixel8383, 

1) can you tell me what version you are basing these remarks on?
2) I can't see a particularly good way to implement this. Could you describe the UI required for this? How does one start with TOTP list only, then move to Folder Hierarchy? Wireframes or something might be helpful.

-Mark

**Comment by pixel8383** [comment]
1. the version is 1.35.0 - What's funny is that now that I enabled "view as -> folder hierarchy" I cannot revert back to "TOTP List" (setting is changed but the view doesn't change). I tried to close the app and open it once again.
2. I was expecting to get a summary view of all the TOTP records listed. On top of the list the "search bar" could be useful to browse the entire database (groups or records). Searching a group should show you the entire records/sub-groups stored. The TOTP list (in my idea) should be showed only on the main/first view.

**Comment by mmcguill** [comment]
1. Thanks for the bug report. 

I have one last trick which should fix the Smooth Scrolling issue I believe, I'll get it in in the next release or two.

2. Yes, ok, I think that search could switch back to normal Folder Hierarchy view I suppose. I think that would work for most people. I'll create a separate issue for that.
