### ISSUE TITLE
iOS: Search Bar Repositioning Glitch

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#135]
The search bar doesn’t seem to reposition correctly when I search for an entry, select the entry to view, and then return to the search screen. The search bar is position lower than it should be which leaves a large white space gap at the top. It reverts back to normal if I press cancel on the search bar. I’ve sent a short screen recording to your support email.

**Comment by mmcguill** [comment]
Thanks for the bug report @shad0whawk

**Comment by shad0whawk** [comment]
Appears fixed...thanks! Closing...
