### ISSUE TITLE
Improved XKCD/Diceware Password Generation

### ISSUE THREAD

**Issue by hcksw** [mmcguill/Strongbox#136]
Hi Mark.
Firstly thank you for a great product! I use it on my iphone and works so well.
I have a question/suggestion. It's not clear what dictionary you are using for the XKCD password generation. On your github you have a resources folder with a few different dictionaries but I don't think it's using all of them. My guess is that you are using the Google one and not the diceware/EFF ones. Could you clarify? Also could you confirm the total words being used. Any particular thoughts/reasons for using the  dictionary that you have chosen?
As perhaps a long-term suggestion, would is be possible to give the user a choice of dictionary, which KeePassXC allows for example using a dropdown menu. It would be very useful to chose, especially the EFF ones, which I quite like.

**Comment by mmcguill** [comment]
Hi @hcksw, thank you! 

Yes, you're right, this isn't clear. The dictionary used at the moment is the Google one and this should be explicit. The number of words is 10,000. No real particular reason, I wrote the code quite a while ago and wasn't aware of Diceware method, and had only seen this method via the XKCD comic. So I just searched for a relatively clean word list and I think it was maybe the first one I came across.

I have an item on the list to expand/improve the Password Generation capabilities with things like Diceware and many different dictionaries and languages, which should hopefully be coming along in the next few weeks and this will/should be very clear in the UI. Keep an eye out for that!

In fact, let's make this issue the tracker for that... That way you'll get a notification when it's done

**Comment by mmcguill** [comment]
Hi @hcksw - This should be available for you now in Mac and iOS. Hopefully a good selection of dictionaries there for you, and the ability to use multiple. Please close off this issue if you're ok with the implementation. Cheers!

**Comment by hcksw** [comment]
Hi,

I just tried this update yesterday and it works really well. Huge thanks. I’ll close the issue. 

Alan 

PS I signed up for a one year sub also. Great app!

**Comment by mmcguill** [comment]
Thank you, the support means a lot!
