### ISSUE TITLE
iOS Bug:  Auto Fill Cache File Missing

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#142]
I'm opening this issue as a placeholder while I gather additional information.  I seem to have an issue with my AutoFill cache going corrupt.  It's happened three times in the past week.  Each time I've had to go into the database and disable/enable AutoFill and offline caches.  That seems to fix the issue until it happens again.  The only commonality and precursor I've discovered so far is that I updated the database on my device shortly before this happened.  My database is opened from and and syncs to OneDrive.  I'll play around with it a bit and post back.  I'll also attach a screen shot in the next reply because it's on my phone.

**Comment by shad0whawk** [comment]
Screen shot...
![23EB8C8E-F972-43F9-B360-A3C27110B7C5](https://user-images.githubusercontent.com/6074105/59624266-89829580-90f3-11e9-8404-99ef3c442a12.png)

**Comment by mmcguill** [comment]
Thanks for the report @shad0whawk . Do you have an exact set of reproduction steps I could use to achieve the same effect, is it 100% reproducible or intermittent?

**Comment by shad0whawk** [comment]
No I haven’t had time to play around with it and figure it out yet. I’ll test it and see if I can reproduce it. I just wanted to give you a heads up on it in case someone else is seeing it as well.

**Comment by shad0whawk** [comment]
Well it happened again.  It was working fine since the last AutoFill switch toggle. I made several changes to my database to include adding and modifying a few entries. I this took place over several saves to the database. The database was also closed and retrieved a couple of times as well during this process. Suddenly I get this same error message again. Reopening the database to update the AutoFill cache updates the cache denoted by the update time in the database settings, but doesn’t fix the issue. Disabling/enabling AutoFill cache solved the issue until the next time. I only have one database that’s setup for AutoFill.

**Comment by shad0whawk** [comment]
So this keeps occurring and it seems to be an issue with the Database Autofill and/or Offline Cache Settings. 

Interesting observation while currently having this issue. I have multiple databases with the same Github entry. I only have one database enabled with Autofill with one entry for Github, but when I use Autofill, that entry shows up 9 times in the Autofill selection list for Strongbox. If I reset the Autofill in the database, it only shows 1 entry. If I open the other database which has Autofill turned off and then check safari again, the Github entry count starts increasing. It’s almost as if one of these settings isn’t working correctly. I can easily replicate this each time. Eventually the cache goes corrupt.

**Comment by shad0whawk** [comment]
To piggyback my last comment, the off-line cash is enabled on the other databases.

**Comment by mmcguill** [comment]
Thanks for the extra detail @shad0whawk, if you could, it would be great if you detailed exact steps to reproduce from scratch. I couldn't get it to happen when I tried.

**Comment by shad0whawk** [comment]
So I turned off Offline Cache in the other databases and it’s still doing it. It seems to reread the databases when I select Autofill in Safari (I can see it flash) and then multiple entries appear. They grow over time.

**Comment by shad0whawk** [comment]
Ok so here goes...

Setup:  
Same database hosted on OneDrive linked 3 times; one as a read/write with Autofill and Offline Cache enabled, another as read only (has to do with my Keepass syncing) with Offline Cache enabled, another that uses the TOTP view with Offline Cache enabled, and one more that is for testing with neither enabled. I keep all things in one database so the new views are useful. The testing database contains different entries. The Github entry appears in all of them and multiple times in the testing one. 

Steps:
1.  Open Strongbox and turn off/on both Autofill Cache and Offline Cache
2. Exit database and reopen
3. Open Github login website in Safari
4. Tap password field
5. Tap key icon to show matches form Strongbox — entry appears once
6.  Switch to Strongbox reopen same database and repeat steps 4 and 5 results in no change to match list—expected behavior
7. Switch to Strongbox and open the second database and repeats steps 4 and 5 results in two identical match results—not expected
8. Switch to Strongbox and open the third database and repeats steps 4 and 5 results in three identical match results—not expected
9.  Switch to Strongbox and open the testing database and repeats steps 4 and 5 results in 6 identical match results—not expected

Does that help?

**Comment by shad0whawk** [comment]
BRW I can replicate the behavior on two different phones

**Comment by mmcguill** [comment]
There seem to be 2 separate issues here. Let's try deal with the Auto Fill Cache file missing error here, and if you could, please open a separate issue for the duplicate entries...

Do you have an exact set of repro steps for the Missing cache file? I couldn't reproduce.

**Comment by shad0whawk** [comment]
Unfortunately no it just happens eventually at some point when I try to Autofill.

**Comment by shad0whawk** [comment]
Ok so I did steps 1-9 from above and opened all of the databases, added an entry to the test DB, closed it, tried logging into Github resulting in the Autofill Cache error. I’ll try it again from scratch.

**Comment by shad0whawk** [comment]
I followed steps 1 to 6 resulting in a single entry that works. I then did step 7 and selected the first entry and it worked. Then I sketched the second entry and got the corrupt cache error. The first entry continues to work but the second one does not. I can consistently replicate the issue now. Both issues seem to be linked together, but I did create a separate ticket for the other one.

**Comment by mmcguill** [comment]
Ok, will try and reproduce this over here shortly.

**Comment by shad0whawk** [comment]
Ok I sent you a video detailing the error.

**Comment by shad0whawk** [comment]
Seems fixed as well. We can leave that annoying issue behind :-) As always, I appreciate it! Closing...

**Comment by mmcguill** [comment]
Great to hear it :)
