### ISSUE TITLE
Change font in notes to one that makes it easier to see which character is used

### ISSUE THREAD

**Issue by Ben-Voris** [mmcguill/Strongbox#143]
I use notes for secondary passwords and sometimes I must type them into a device that doesn't have access to my Password Safe. The current font makes it difficult to see differences between zero `0` and uppercase `O` and between uppercase `I` and lowercase `l`. 

Please change the font to one that makes these differences easy to see. The font used in the password box works well for me.

**Comment by mmcguill** [comment]
Hi @Ben-Voris,

There is a preference you can use that will change the font used in all Fields to the "Easy Read" one (actually uses the System Menlo font). Would that work for you?

To change it, go to any item details view and tap the Preferences icon (Top Right, beside the Edit button). Then find the "Easy-Read Font on All Fields" switch. Turn that on.

![image](https://user-images.githubusercontent.com/344791/59704013-26fbc900-91c9-11e9-927f-093f38cb8add.png)

**Comment by Ben-Voris** [comment]
That does the trick on my iPhone, but that option is not available on my iPad. Please, would you add it?

This seems to affect all entries in a safe. Is that true?

**Comment by mmcguill** [comment]
Should be available on your iPad? Unless, what version of iOS are you using, is it pre iOS 11?

Yes, it is a Application-Wide setting affecting that Item Details view for all entries. It doesn't affect the underlying data of course, if that's what you mean, just the font used to view.

**Comment by Ben-Voris** [comment]
Strongbox 1.30.0 iOS 12.3.1. iPad Pro (10.5-inch)   Meatballs are not there.   My iPhone had version 1.3 2.0. I deleted Strongbox and reinstalled it, and got version 1.3 2.0. Now I can display easy to read it.

I kept looking at database preference and didn’t notice the meatballs on the entry.
