### ISSUE TITLE
iOS Bug:  Application Crash Related to Key File Management Setting

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#144]
I’m consistently able to crash the application if I open the application > select Preferences > Key File Management > and tap on the key file I have listed.  I can swipe left and the key file options appear without crashing it.

**Comment by mmcguill** [comment]
Yep, see the issue, will be an easy fix I'll get done in the next release.

**Comment by shad0whawk** [comment]
Looks fixed...thanks! Closing...
