### ISSUE TITLE
iOS: UI Observation

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#145]
I’ve noticed that there’s an noticeable delay in drawing/rendering the top-most row in the database when drilling down to a child folder/entry AND the search bar is present on the parent screen.

**Comment by mmcguill** [comment]
Yes, noticed it too. Thanks @shad0whawk

**Comment by shad0whawk** [comment]
The transition is nice and smooth now. Thanks! Closing...
