### ISSUE TITLE
iOS: Make (some) View Preferences per database rather than global

### ISSUE THREAD

**Issue by mmcguill** [mmcguill/Strongbox#146]
Preferences Like:

- Sort Field
- Sort Order

**Comment by milesmcclane** [comment]
Great idea, there are probably a few more things I could think of that could be changed in this respect, now it’s in my mind.

**Comment by mmcguill** [comment]
For sure, feel free to note them here

**Comment by shad0whawk** [comment]
I think everything under the “View Preferences” menu should be database specific in addition to what you have already listed or completed.

**Comment by milesmcclane** [comment]
I agree, being this flexible - as long as it’s a possibility technically- is the best approach.

**Comment by shad0whawk** [comment]
And I say that lightly not knowing how much effort that would take. I think the top three for me would be the View As (already done), Sort Order, and Item Subtitle.

**Comment by mmcguill** [comment]
All of these settings are now per database with 1.33.0... 👍
