### ISSUE TITLE
iOS:  TOTP Setup Question and Request

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#149]
I was setting up some TOTP entries and noticed some inconsistencies in which custom fields are created depending on the type of TOTP being setup when I scanned a QR code.  If I scan a standard 30-minute 6-digit type code, Strongbox doesn't create the TOTP Settings field, but it seems to do it for non-standard configurations.  I realized this when I exported my Authy tokens without converting the time period correctly.  I ran into a compatibility issue with the KeePass plugin I use because the TOTP Settings field didn't exist.  It was an easy fix to create the field manually, but I was wondering why the difference and could it be added to the standard process.  I hope this makes sense since I've deleted the previously exported tokens so a bit hard to recreate at the moment.

**Comment by mmcguill** [comment]
Yes, I'm actually not sure why, but there is code in there to not create the TOTP Settings field if it is using Default settings... I don't remember why right now, and since it's perfectly safe to create this anyway, I'll fix this in the next release.

**Comment by mmcguill** [comment]
Should be good with 1.33.0 @shad0whawk

**Comment by shad0whawk** [comment]
I’ll test it out later but I’m guessing it’s good. Thanks! Closing...

**Comment by MaivKhanh20181** [comment]
1
