### ISSUE TITLE
iOS: Auto-complete function complicates editing of fields

### ISSUE THREAD

**Issue by Slummi** [mmcguill/Strongbox#154]
The auto-complete function is a nice feature for entering a new string, but it complicates editing (single characters of) an existing string, because there's no way to decline the auto-complete suggestions.

Example:
The current URL field is http://www.google.com.
When you try to insert a 's' to change the protocol from http to https the auto-complete function overwrites the complete URL starting from that position where you try to change something.
In this example the auto-complete function would overwrite everything after 'https' and makes suggestions like this: https://www.amazon.com, because there's already another database entry with that URL.

This happens for all fields with auto-complete, but you may not notice for other fields, because there are not so many alternative entries than for the URL field.
I think it would be better, if the auto-completion only works when the cursor is at the end of a string.

**Comment by shad0whawk** [comment]
I’ve never noticed this before, but I was easily able to replicate it.  It does wipe out the current URL and replaces it with something completely different which is not ideal.

**Comment by mmcguill** [comment]
Yes, I see the issue too. First time I've noticed it. Thanks for the report.

**Comment by Slummi** [comment]
Tested in 1.34.0. Editing fields is working as expected, now. Thanks for the quick fixing!

**Comment by mmcguill** [comment]
For sure.
