### ISSUE TITLE
AutoFill uses credentials of another entry than the selected one

### ISSUE THREAD

**Issue by Slummi** [mmcguill/Strongbox#155]
I had a strange bug, today. Unfortunately I can't reproduce it.

I used the AutoFill function to fill in the credentials on a webseite in Firefox.
AutoFill found exactly one matching entry for the URL of the website. I chose that entry and Strongbox filled in the credentials of another database entry that I had edited before.

As already stated, I can't reproduce this at the moment. @mmcguill Do you have any idea, why this happened? Maybe a problem with the cache? I have recently made extensive changes to the database (edited many entries and added some new).

**Comment by mmcguill** [comment]
Hi @Slummi, no I'm afraid I can't offer any insight... I've not seen this occur myself, but I have noticed sometimes Apple's version of the AutoFill database can take a while to refresh, which is what you could be seeing.

**Comment by mmcguill** [comment]
@Slummi any news on this, is it still happening?

**Comment by Slummi** [comment]
No, it didn‘t happen, again. Seems to be a one-time bug. Think we should close this for the moment.
