### ISSUE TITLE
iOS Notes Text Selection Suggestion in Edit Mode

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#156]
This is in reference to editing the notes text within an entry.  Standard iOS behavior to select a full word is to double-tap it.  When the entry is in edit mode, the double-tap still copies the entire field like it does when it's in not-edit mode.  The current behavior requires me to tap and hold the word and then choose "Select".  Would it be possible to change the behavior so that the double-tap in edit mode does not copy the full field, and instead allows us to select the full word that is selected?

**Comment by shad0whawk** [comment]
Thanks for adjusting this as well.  Closing...

**Comment by mmcguill** [comment]
Nice
