### ISSUE TITLE
iOS Search Functionality Question

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#157]
I’ve noticed that if I search for a term, enter an entry from the search results, and then back out of it, the previous search results all disappear. Sometimes I select an entry in the search results to quickly view and then want to look at the next one in the list, but I have to redo the search each time. Is this intended behavior or can it be configured so that the search results persist until the user presses cancel?

**Comment by shad0whawk** [comment]
Thanks for adjusting this! Closing...

**Comment by mmcguill** [comment]
Excellent news :)
