### ISSUE TITLE
iOS feature request: use camera add attachment 

### ISSUE THREAD

**Issue by milesmcclane** [mmcguill/Strongbox#158]
I have an iOS feature request. I would find it useful to be able to use the camera in the ‘add attachment’ field, hopefully bypassing the picture from being added to the camera roll.

**Comment by mmcguill** [comment]
Should be very doable, not sure about the camera roll, I'll look into this shortly...

**Comment by mmcguill** [comment]
Hi @milesmcclane - This should be available for you now with 1.35.1 - You can select Camera from the list of methods to add an attachment. Photos are not saved to the Camera Roll. Please close off if happy with the fix

**Comment by milesmcclane** [comment]
Excellent news! Very useful thanks.
