### ISSUE TITLE
Auto-open single database file

### ISSUE THREAD

**Issue by marcelstoer** [mmcguill/Strongbox#159]
If Strongbox only knows about a single database file (i.e. the only one opened in the past) it should open that one automatically rather than bringing up the select-database-file dialog.

**Comment by mmcguill** [comment]
Have you seen the "Quick Launch" feature @marcelstoer - This may be what you're looking for. If you tap the "rocket" icon in the top left corner you will enter this mode. It will automatically ask you to unlock on activation.

**Comment by marcelstoer** [comment]
Sorry me not undastand...

Thanks Mark, could you add a screen shop please?

**Comment by mmcguill** [comment]
Sure... just tap on the button highlighted in Red below:

![image](https://user-images.githubusercontent.com/344791/60597272-428dd480-9d70-11e9-9a4b-f0dd0ef5d6d0.png)

**Comment by marcelstoer** [comment]
Thanks, we ain't talking about the same platform obviously 😜 

<img width="603" alt="Screenshot 2019-07-03 at 16 48 50" src="https://user-images.githubusercontent.com/624195/60601589-a76a1e80-9db2-11e9-80f5-024fcf3adc0b.png">

**Comment by mmcguill** [comment]
Haha, yep, we were definitely talking past one another there! 👍 

I'm curious would the following Mac wide setting work for you? If you close an application there is a setting in System Preferences -> General, about restoring previous document windows. It looks like this (highlighted in Red):

![image](https://user-images.githubusercontent.com/344791/60603885-327bf200-9d7c-11e9-89f8-defe87e71c44.png)

If you turn that off (as in the screen shot) Strongbox will open up the last used documents at startup. Would that work for you, or are you seeking slightly different behaviour?

**Comment by marcelstoer** [comment]
Oh, I didn't know about this flag, thanks. It does have the desired effect.

However, I would still prefer an application setting for this like on iOS. "Close windows when quitting" does basically make sense to me as a system-wide setting.

**Comment by mmcguill** [comment]
Understood. Not a bad idea.

**Comment by mmcguill** [comment]
Hi @marcelstoer this should be available for you in Mac 1.9.0. See the little checkbox on the Databases Manager:

![image](https://user-images.githubusercontent.com/344791/60920134-15a05c80-a25d-11e9-8c5b-70f024fe14ad.png)

Please close if happy with the result :)

**Comment by marcelstoer** [comment]
Ok, will give it a try when macOS feels ready to send that update down the pipe. "Primary Database" happens to be the first in the list top-down?

**Comment by mmcguill** [comment]
Yep, for the moment at least... possibly configurable at some stage later if people feel the need.

**Comment by mmcguill** [comment]
Closing out

**Comment by marcelstoer** [comment]
That's fine. I haven't found a way to force-update apps from the app store (or at least trigger a manual update check) but I trust it'll do what it looks like it should do 😄
