### ISSUE TITLE
iOS Bug: View As Bug

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#161]
Database View As setting is not respected if “Show Recycle Bin” deselected.  Both TOTP List and Flat List views break if I have either enabled and deselect “Show Recycle Bin”.  The view reverts back to the Folder Hierarchy view until I select “Show Recycle Bin” again.

I think this is related to @pixel8383’s last comment in issue #132. None of the other settings seem to impact the view setting negatively for me.

**Comment by pixel8383** [comment]
I do confirm, I have "show recycle bin" disabled on my app.

**Comment by mmcguill** [comment]
Yes, see the issue alright. Nice catch. I'll have it patched in the next release.

**Comment by mmcguill** [comment]
This should be fixed now, I'll leave open for your to confirm and close @shad0whawk

**Comment by shad0whawk** [comment]
Looks good! Btw I like the new icon. It’s matches the rest of the interface very nicely.

**Comment by mmcguill** [comment]
Thanks @shad0whawk! Was a bit nervous about the new icon/logo but I'm coming to like it more than the last
