### ISSUE TITLE
iOS Bug: Custom Icons Not Showing

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#162]
I added additional icons to Keepass from the Keepass plugins page—specifically these PNG icons at this link:  https://keepass.info/extensions/base/clienticons/ClientIcons_Diego.zip. They show up in Keepass under the custom icons section, but they are not showing up in the default list or the custom/favicon list in Strongbox.  Is this an icon format issue or something else?  The favicons I’ve downloaded show up without any issues.

**Comment by mmcguill** [comment]
Hi @shad0whawk, how do you add these? Strongbox will only keep icons around that are referenced by an entry/group or historical entry. This is how I assumed things worked, but it is possible that this is an incorrect assumption. I assume if you use one of these icons in an Entry it will be visible in Strongbox?

**Comment by shad0whawk** [comment]
Hmm I’ll have to check this out again on Keepass.  I’ll try using one of the additional icons and see if it shows up in Strongbox. I would have assumed that they’d be available to select from in Strongbox but I guess it depends how/where the icon is stored.

**Comment by shad0whawk** [comment]
So I guess this isn’t a bug so I’ll close it. I associated one of these with an entry and it shows up as available but not the others.I assumed that all available icons in the database would be available to use, but that is not the case. Either way no big deal just an observation.

**Comment by mmcguill** [comment]
Yeah, I mean, it's sort of a feature. So Strongbox at the moment trims any unused custom icons. It seems like maybe KeePass doesn't? Is that correct? For example if you add those icons to your database somehow using KeePass, then say open the database in Strongbox (without making any changes (the trim happens on save)), do you then see them in the database as an option? 

It is not entirely necessary to trim the icons, I've just assumed it's better for database size to remove them.
