### ISSUE TITLE
iOS Feature Suggestion:  Confirmation to Remove Database

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#169]
It would be useful to have either a confirmation prompt or option to enable one when swiping left on a database in the databases list with the intent of removing it. The swipe left is very touchy and it’s way too easy to go a tad bit too far.  I’ve almost unintentionally removed a database a few times when trying to use this method to rename or view offline cache. Just a suggestion...

**Comment by mmcguill** [comment]
Do you not get:

![image](https://user-images.githubusercontent.com/344791/61976940-b52a5280-afb2-11e9-95aa-9082e9610544.png)

**Comment by shad0whawk** [comment]
Wow talk about having an off moment... 

I tried it again and I do receive the prompt.

**Comment by mmcguill** [comment]
No worries!
