### ISSUE TITLE
Unable to Cancel Autofill Touch ID Prompt

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#170]
I may have stumbled onto a small bug on devices using Touch ID using the following steps:

1.  Navigated to a website with login parameters
2.  Selected the password field where AutoFill prompted me with a list of values
3.  Selected one of the matching entries
4.  Selected "Cancel" when prompted by Touch ID

This resulted in an unresponsive Safari application with the Strongbox logo and name in the middle of the screen with "Loading..." beneath it.  I have to force quit the application to be able to use it again.  I can replicate this every single time.  No issue if I press my finger on Touch ID to authenticate.  My iPad is running iOS 12.4.

**Comment by mmcguill** [comment]
Ok, will look into this shortly. Thanks for the report.

**Comment by georgesnow** [comment]
I hd similar experience jsut recently after I broke the Touch ID on my phone and couldn’t get past the Touch ID. To just type my whole password for the database.

**Comment by mmcguill** [comment]
Should be good for you with 1.37.1

**Comment by shad0whawk** [comment]
I’d love to say it’s fixed, but it still happens on 1.37.1 and my iPhone 8. Same steps, same result. If I switch to another app using task manager or close it with the home button, then switch back to Safari, it’s no longer frozen.

**Comment by mmcguill** [comment]
Ok, weird. Will take a look

**Comment by shad0whawk** [comment]
Looks to be fixed now with the latest update.  Thanks!

**Comment by mmcguill** [comment]
Great! Cheers!
