### ISSUE TITLE
Safari - Auto Fill - Create new entry didn’t save

### ISSUE THREAD

**Issue by georgesnow** [mmcguill/Strongbox#171]
I had attempted to create a new entry in my keepass database by selecting passwords QuickType option and “create new”. Filled out all the entry pressed done and went back to the database to find it wasn’t saved. Tried 3 times no dice. Database is stored in the strongbox iCloud folder. And is kdbx

**Comment by mmcguill** [comment]
Ok, will take a look, sounds very odd. Did you add it via Files or was it just picked up automatically/created on this device?

**Comment by georgesnow** [comment]
I added it to the iCloud folder manually on my Mac a while back. 2 other notes I changed the username and password manually from the the auto created ones. I also changed the title. I confirmed a second time with same database I get the same behavior

**Comment by mmcguill** [comment]
Hi @georgesnow - I can't reproduce this issue here. Any iCloud safes I create get updated if I add anything via the Auto Fill extension... Could you create a new iCloud database and see if that is affected?

Perhaps a quick sign out/sign back to iCloud on your device is worth a test too, to see if that fixes?

**Comment by georgesnow** [comment]
So it only happens with databases that autofill part of a new  entry. So user name is auto populated by strongbox with an email and I delete the email as the user name and type a new one. I will try to do screen recording when I get a chance

**Comment by mmcguill** [comment]
Ok, it sounds like you might be changing, say, the username inside Safari? Is that right? 

There is currently no way to "Edit" an entry, only to Create a brand new one from within the AutoFill extension. 

Editing the field in Safari (for example) will not update the database (Strongbox has not access to that edit/field).

**Comment by georgesnow** [comment]
It’s actually within the strongbox ui. So select “passwords” from QuickType. Click cancel then select “create new” top right. For new entry. The user name has auto populated with my email, which I believe is the “autofill for the database” (not what’s entered  in the safari ui). I delete the user name and type my own. Change the title and password. Click done. Open strongbox app select same database entry isn’t there. 

I think I need to do screen capture to really demo it

**Comment by mmcguill** [comment]
Yep, ok, would definitely help.

**Comment by georgesnow** [comment]
Closing this cause it only happens with one database. And can’t seem to figure what it’s different about the database. I will open new ticket if I can figure out better what I am doing differently
