### ISSUE TITLE
Can't connect to OneDrive on iOS

### ISSUE THREAD

**Issue by llaske** [mmcguill/Strongbox#173]
I'm trying to use Strongbox on iOS with a database stored on OneDrive.
It failed as soon as I'm clicking on OneDrive telling "Error Selecting Storage Location - bad request". See screen capture below.

![image](https://user-images.githubusercontent.com/981841/62126889-05662500-b2d1-11e9-8645-d4c07dd8ac82.png)

**Comment by mmcguill** [comment]
Hi @llaske - I can't reproduce this at the moment. Can I ask is this a personal or a business account? Is it still an issue for you now?

**Comment by shad0whawk** [comment]
I use a OneDrive setup for my database and have not encountered this issue yet. It’s been reliable and stable on my end.

**Comment by llaske** [comment]
@shad0whawk it's a personal account. To be clear it worked one my account before I've activated the OneDrive two-factor authentication. Is there something specific to do when two-factor authentication is activated?

**Comment by dan-el** [comment]
You might need to set up an APP PASSWORD. Look here: https://account.live.com/proofs/manage/additional?mkt=en-US&refd=account.microsoft.com&refp=security&fref=moreOptions

**Comment by llaske** [comment]
@dan-el thanks for your answer but App Password can't help here.
OneDrive app works well on my device with the two-factor authentication and I can even access to the StrongBox OneDrive authentication because it failed as soon as I'm clicking on OneDrive storage as location. So I can't type a password at all.
Here's a short video to show you what happens.

![strongbox](https://user-images.githubusercontent.com/981841/62213328-f354b700-b3a2-11e9-9dff-01147aa685f8.gif)

**Comment by dan-el** [comment]
I see. I tried it on my iPhone SE running iOS 12.4 and the „add existing database“ -> „onedrive“ path leads me to the login form of onedrive which looks good.

Maybe your login credentials are cached on your iPhone. You could try „offloading“ the app via „Settings/General/iPhone Storage/strongbox/offload app“ and then try again.

Be sure to have your database in a safe place first.

Just an idea.

**Comment by llaske** [comment]
Offloading the app didn't help but I've finally uninstalled and reinstalled the app and it works now 👍 
FYI, there is nothing special to do for two-factor authentication, everything is handle by OneDrive during login process.
Thanks all for your help and for this cool app 👏

**Comment by mmcguill** [comment]
Really glad you got this sorted @llaske - Seems like some kind of state/cookie issue with the OneDrive library here, that obviously got cleared when you uninstalled/re-installed. 

I wonder if changing to 2 factor was what caused the issue in the first place.

Thanks @shad0whawk and @dan-el for your help with this.
-Mark

**Comment by speedfire514** [comment]
Same issue. I did not change anything related to the authentication on OneDrive (already have 2FA activated). The only way to solve the problem was reinstalling the app.

**Comment by strongbox-mark** [comment]
Just a note, in case others come across this issue. 

There is actually a way to clear the cache/session token. It’s under Preferences > Cloud > Cloud Sessions > Clear OneDrive Session.

**Comment by mjvdhoek** [comment]
Had same error today. Strongbox running fine on two iphones but had this problem in iPAd.
**Deleting the app and re-insttalling it resolved the issue.**

**Comment by strongbox-mark** [comment]
Hi @mjvdhoek - Did you try the solution mentioned above:

Preferences > Cloud > Cloud Sessions > Clear OneDrive Session

before uninstalling?

**Comment by mjvdhoek** [comment]
> Hi @mjvdhoek - Did you try the solution mentioned above:
> 
> Preferences > Cloud > Cloud Sessions > Clear OneDrive Session
> 
> before uninstalling?

Hi...
no... might have done the trick.... thanks pointing that out. will try next time if it occurs!

**Comment by strongbox-mark** [comment]
Yes, would like to know if this fixes things for people. What version are you running by the way?

**Comment by mjvdhoek** [comment]
> Yes, would like to know if this fixes things for people. What version are you running by the way?

Model: iPhone
CPU: arm64 v8
System Name: iOS
System Version: 14.1
Ep: 1586857179
Flags: P[0[-1]110[26]0011]
App Version: com.markmcguill.strongbox [1.49.24 (2976)@9f06a52]
