### ISSUE TITLE
App hunging when using safari as app

### ISSUE THREAD

**Issue by defragmentator** [mmcguill/Strongbox#174]
When using websites like windguru as app like in this tutorial https://www.windguru.cz/apps.php Strongbox is unable to fill user and password. It hangs on Touch ID screen. When using the exactly same site but directly from safari it works fine. By icon created as in tutorial - does not work :/

**Comment by mmcguill** [comment]
As far as I can see this is not supported by iOS Safari for these Progressive Web Applications - which is why it's crashing. Source: https://love2dev.com/pwa/ios/

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/344791/62173082-5d655180-b2fa-11e9-8e9c-0a62f9e64dbf.png">
