### ISSUE TITLE
Field References

### ISSUE THREAD

**Issue by mmcguill** [mmcguill/Strongbox#18]
https://keepass.info/help/base/fieldrefs.html

**Comment by shad0whawk** [comment]
I would love to see this one implemented in a future release since I find using field references in my database to be beneficial and simplifies maintenance when you have multiple sub accounts that link to the same master account.

**Comment by shad0whawk** [comment]
It would be very helpful to have this feature implemented so I don’t have to flip between the entry that contains the URL, account information, and field reference value with the entry that contains the master password referred to in the field reference. Thank you!

**Comment by shad0whawk** [comment]
Hey Mark. Any update on where this feature sits on your road map?

**Comment by mmcguill** [comment]
Hi @shad0whawk, hoping I'll get it in in the next 3 or 4 weeks

**Comment by shad0whawk** [comment]
That would be awesome to include that feature. Thanks!

**Comment by mmcguill** [comment]
Hi @shad0whawk, this should be working for you now on iOS with version 1.26.0. Keeping ticket open for Mac work... 

Some extra detail here: https://strongboxsafe.com/hrf_faq/does-strongbox-support-keepass-placeholders-and-field-references/

**Comment by shad0whawk** [comment]
Thanks! It works great for the existing field references I have in my database. 

I’m assuming the ability to create them in Strongbox is probably out of scope for this request unless you know the syntax and UUID of the referenced entry.

**Comment by mmcguill** [comment]
> I’m assuming the ability to create them in Strongbox is probably out of scope for this request unless you know the syntax and UUID of the referenced entry. 

Yes I think so, it's a sort of advanced feature, so I'd expect users to be able to manage this themselves. The UUID is important to expose but that's already requested in #86

**Comment by mmcguill** [comment]
Mac 1.7.0 now supports Field References and PlaceHolders
