### ISSUE TITLE
Support QuickType Auto Fill

### ISSUE THREAD

**Issue by mmcguill** [mmcguill/Strongbox#20]
https://developer.apple.com/videos/play/wwdc2018/721/

**Comment by Ben-Voris** [comment]
How is this different from https://github.com/mmcguill/Strongbox/issues/9?

**Comment by mmcguill** [comment]
Basically improves and streamlines the experience, no UI involvement basically, so option to auto login appears inline in the keyboard as part of 'Quick-Type' area, no touch-id/face-id/password required.

**Comment by georgesnow** [comment]
I am not sure if this is part of this or it falls under the general auto fill extension for iOS. The ability to add new entry if one can’t be found. Example being there is no QuickType entry available or entry without QuickType. So If you end up in the search list view. There could be an add button to create a new entry for the site.

**Comment by mmcguill** [comment]
Yes, I'll consider this a feature request, and get it on the backlog

**Comment by mmcguill** [comment]
> I am not sure if this is part of this or it falls under the general auto fill extension for iOS. The ability to add new entry if one can’t be found. Example being there is no QuickType entry available or entry without QuickType. So If you end up in the search list view. There could be an add button to create a new entry for the site.

**Comment by georgesnow** [comment]
Just curious have you given this feature any further thought?

**Comment by mmcguill** [comment]
Hi @georgesnow, definitely, super high on the list, think it would be a very nice feature indeed. Hopefully get to it in the next few weeks.
Cheers,
-Mark

**Comment by mmcguill** [comment]
This is available now with 1.25.0. Let me know if you have any issues.

**Comment by georgesnow** [comment]
awesome! I will keep an eye out for update. curious how does it operate with multiple KeePass database? do you have to pick one or is it all? I just ask cause I have 2 databases want to make sure I understand how it works before I report an issue thanks

**Comment by mmcguill** [comment]
Hi, 

You can control whether a database takes part in QuickType, and also there is a master on/off switch in Settings to turn them all off. 

There is a bit of an issue, which is sort of unavoidable (due to the design of the QuickType API) when working with multiple databases which is when you turn off on of your databases from QuickType, it is not possible to selectively remove the entries from the QuickType database. It is only possible to remove all entries or none. 

I've err'd on the side of convenience here, and left those entries in place, but the whole QuickType database can be cleared by using the Master On/Off switch in settings if this becomes an issue. So you could flick the master switch off then on, re-open the database you wanted to participate in QuickType and it will populate the QuickType database with only those entries.

Hope that makes sense,
-Mark

**Comment by georgesnow** [comment]
yes it does. i went down a rabbit hole reading about the Quicktype API. when i was using a different password manager and didn't do that.

**Comment by georgesnow** [comment]
Updated this evening and so it is working great with one database but not the other. And it’s strange cause I have same entry in both one database QuickType works and matches. The other it won’t. I tried creating new records, turning on and off cache, auto fill all the together. The one database always works and the other won’t. Both are stored in iCloud. So far I can only find 2 differences.

The one that works is shared via iCloud with another person and was created with MacPass.

The other says it was created with strongbox and is not shared.

**Comment by shad0whawk** [comment]
Hmm so how is this supposed to work? I have autofill enabled globally and on my database in Strongbox that was created in Keepass. I have yet to see QuickType provide me with an option to fill sourced from Strongbox. It works fine from iCloud Keychain because I get the suggestion which shows the source.

**Comment by shad0whawk** [comment]
I keep trying but it doesn’t seem to work. One instance of my database is stored on OneDrive, and a copy of that instance is also copied into Strongbox locally. I’ve enabled both but neither seem to work.

**Comment by georgesnow** [comment]
Might be red herring but did you happen to notice where it says the database was created by? Ie strongbox, keepass, Macpass basicly the clien

**Comment by shad0whawk** [comment]
My primary database shows “Keepass” as the generator. I also created a test database in Strongbox a few test entries and it shows “Strongbox”.  Unfortunately neither one works for QuickType. What’s weird is that I also have 1Password (although I rarely use it) and that doesn’t seem to generate entries for QuickType either.  The be made sure that whatever I’m testing is selected in the Autofill Passwords setting in iOS Settings.

**Comment by shad0whawk** [comment]
FWIW I tried it on my work phone and my wife’s phone and can’t get it to work. All iOS 12.2 but different hardware models. Can’t get 1Password QuickType to work either on my personal or work phone—all different iCloud accounts.

**Comment by shad0whawk** [comment]
Sorry for so many posts...

Well I was able to get 1Password to work finally on multiple devices by turning it off and on a few times. When I set 1Password to Autofill it shows “Updating Passwords...” and then it works. I’ve tried doing the same with Strongbox but no visual indicator which is probably specific to 1Password.  I’ve even turned off all Autofill related functions within iOS settings and Strongbox and turned them back on and still no luck.

**Comment by shad0whawk** [comment]
One more interesting observation. If I create a new Keepass 2 Advanced database in Strongbox, I cannot get the QuickType to work. If I create a new Keepass 2 Classic database in Strongbox, IT WORKS PERFECTLY???  So maybe something in the difference between the two database structures is causing the issue.

**Comment by limuc** [comment]
I also couldn't get it to work. iCloud Keychain works perfectly.
The database was created with KeePassXC.

**Comment by mmcguill** [comment]
Thanks for the feedback. Seems there maybe some teething troubles. 

@shad0whawk, @limuc, can I ask you about the format of your URLs, are they fully qualified with a scheme, so "https://google.com" rather than just "google.com"?

The format of the DB shouldn't matter at all, and I've been able to create both a classic and an advanced as well as a Password Safe and get them working.

It might also help to make sure you toggle the Strongbox Master switch on/off before you try it out. 

You must also open/unlock the database to populate the QuickType database. 

Also I'm sure you're already doing this but make sure iOS settings are ON for Strongbox too:

![image](https://user-images.githubusercontent.com/344791/55542472-6c7b2080-56c7-11e9-85fc-009062f62984.png)

**Comment by limuc** [comment]
Yes, the URLs are fully qualified. I also tried it with the exact URL (website.com/login) and the generic one (website.com). 

I also toggled the button, unlocked the database and the iOS settings are also on.

**Comment by mmcguill** [comment]
That is strange indeed... I just want to list the conditions here for others just to make it easy to rule out simple things:

1) Using version 1.25.0 
2) on iOS12+ with the iOS AutoFill settings for Strongbox ON
3) Both Strongbox QuickType (Master and Database) toggles ON
4) The entries have non empty Usernames
5) Fully qualified URLs
6) You have Unlocked the Database (required to fill the QuickType database

Could I also ask how many databases you have in Strongbox? I wonder if the issue is related to multiple databases.

**Comment by limuc** [comment]
I did everything you listed there and i have only one database.
Maybe it has something to do with the application you created it, in my case KeePassXC.

**Comment by mmcguill** [comment]
Thanks @limuc, have you tried creating a new DB with Strongbox, does that work? Also, hate to recommend the old classic "restart your device", but could you try that too?

**Comment by georgesnow** [comment]
So I did some testing I found that one I created with Mac pass works and one that I created in the Strongbox iOS app use the express option works But won’t won’t actually auto fill when I select from the QuickType. I test with cacheing on abd off they both worked.   However the older one that I created in Strongbox (I believe with the desktop app) doesn’t seem to work. Encryption and version match those that do work. 
I am going to try and take my older database and see if exporting and re- importing in Macpass fixes it.

**Comment by georgesnow** [comment]
Also I have multiple databases which doesn’t seem to affect which ones work

**Comment by georgesnow** [comment]
Also how does it handle when you have custom fields with multiple urls?

**Comment by limuc** [comment]
@mmcguill
No problem, restarted the device, still didn't work. 
I also created a new database and it works flawless. So it's some problem with my database, don't know if it's possible to fix.
The workaround from @georgesnow isn't possible for me because i don't have a mac.

**Comment by georgesnow** [comment]
![strongboxautofill](https://user-images.githubusercontent.com/12751441/55556796-603a9780-56b6-11e9-8c0e-48be820c7f6f.gif)

this is the behavior i am getting with the newer databases. they provide the option to autofill but fail. however, the one database that worked still works no matter what. it is really strange

**Comment by mmcguill** [comment]
Hi @georgesnow I think this is because there are stale references to older (now removed) database in QuickType. If you toggle the Master Switch Off and then On, that will clear things, and then open your databases up to populate the QuickType cache... does that fix the issue you're seeing?

Definitely need better messaging here.

**Comment by mmcguill** [comment]
> @mmcguill
> No problem, restarted the device, still didn't work.
> I also created a new database and it works flawless. So it's some problem with my database, don't know if it's possible to fix.
> The workaround from @georgesnow isn't possible for me because i don't have a mac.

@limuc I don't think it will have anything to do with MacPass or what client created the database... I believe that's a red herring. But I really wonder what is stopping your database from working. That is indeed very strange. How far in the process do you get? Do you see the suggestion in say Safari if you go to the appropriate website?

**Comment by mmcguill** [comment]
> Also how does it handle when you have custom fields with multiple urls?

Strongbox should pick up URLs in the Notes and Custom Fields and add them to the Quick Type cache too... So should just work

**Comment by georgesnow** [comment]
i did some testing and looks like you are right mark. the client doesn't seem to matter.

ok- i was wondering if entries with multiple URLs was causing the issue.

this is just so weird cause i have database that works. I can even add entries from desktop client and iOS app and they show up as an option to use as QuickType like below and they autofill no problem. but any other database i try to use (or create) won't work properly. 

![Screen Shot 2019-04-04 at 8 38 02 AM](https://user-images.githubusercontent.com/12751441/55560453-3c7b4f80-56be-11e9-813b-3a5b3a906911.png)

**Comment by georgesnow** [comment]
> Hi @georgesnow I think this is because there are stale references to older (now removed) database in QuickType. If you toggle the Master Switch Off and then On, that will clear things, and then open your databases up to populate the QuickType cache... does that fix the issue you're seeing?
> 
> Definitely need better messaging here.

no, it didn't. i created the database within Strongbox(iOS) as test database. QuickType still does what i should above in the gif. so it presents the entry in QuickType but selecting it just shows that white screen briefly. however, i copied that entry into my working database. and it works flawlessly when select it. presents touch id and fills the form.

**Comment by georgesnow** [comment]
i also tried using Strongbox (macOS) added a few entries. Then i went to my iOS device and QuickType again showed the entry, but i get the behavior above still. 

sorry - for so many replies....

**Comment by mmcguill** [comment]
Thanks @georgesnow... that is very strange indeed... I will add some better messaging about what's happening here in the next release, and also I think I will be a bit more aggressive about clearing stale entries. I'll also add some UI indication of Population and Clearing of the QuickType DB.

**Comment by limuc** [comment]
@mmcguill No, i don't even see the suggestion. Tried it multiple times.
But maybe it's just my database, i have this strange problem with the readout of my history (maybe a hint, that something with my database isn't working the way it should?)
![IMG_3842](https://user-images.githubusercontent.com/49267156/55566378-dad9d600-56fb-11e9-87a5-af5a04606b2a.JPG)

**Comment by shad0whawk** [comment]
Hi Mark.  I've been trying everything you suggested but can't get it to work on my existing database.  I created a new test database in Keepass and it works fine.  I then tried to sync my existing database entries with the working new one and it doesn't work with QuickType.  Then I deleted everything in the test database that I synced except for the two test entries and now it works (which is useless since I deleted all my data out of it). 

In your checklist of items 1-5, you mentioned nonempty usernames and websites.  Are you saying every  entry has to have these populated in order to work?  My database contains plenty of entries where one or both are not populated but that's by design.  I would think that it would skip these.

Also, I noticed that while testing a working database, if I change the username of an entry, it wasn't showing correctly in QuickType until I toggled Autofill on/off.

**Comment by georgesnow** [comment]
@shad0whawk turns out the empty username entries don't matter. The working database i confirmed there are 3-4 entries with URLs and passwords but no usernames. And other sites that have username, password and URL Strongbox populated QuickType suggestions

**Comment by shad0whawk** [comment]
So I've narrowed my testing down to a small number of entries.  It appears that it fails if there is a custom field in any entry.  That seems to be the most consistent reason for failure from my testing.  If I remove all entries with custom fields it works immediately and after I toggle the master Autofill switch off/on.  If I add a custom field to an entry, it still works until I toggle the master autofill switch off/on, but it fails after I toggle the master Autofill switch off/on until I remove the custom field.

**Comment by georgesnow** [comment]
is this any type of custom field? ie what about TOTP Seeds?

**Comment by georgesnow** [comment]
when you say "master" are referring the iOS system preferences or the master toggle within the app?

**Comment by shad0whawk** [comment]
Initially a couple of my testing entries had a custom field called "Email" so I deleted it.  Then tried it and it worked.  Then I created a new custom entry within Strongbox called "Test" and it failed, removed it and it worked.  Tried again with "Custom" and same results.  So it seems the name doesn't matter if that's truly the issue.

Master meaning within Strongbox on the app's home screen where the databases are listed.

**Comment by limuc** [comment]
Awesome find @shad0whawk ! Tested it and i had one entry with a custom field, deleted that and it works!

**Comment by georgesnow** [comment]
do any of you have TOTP setup and have it working?

**Comment by shad0whawk** [comment]
That was a pain in the @$$ getting there.  Hopefully, if that's the cause, it can be programmatically fixed to overlook that attribute.

**Comment by georgesnow** [comment]
awesome find....uh yeah that was. i just went through over 300 entries....i am going to try adding my TOTP back in cause it works now for me too without any custom fields of any kind

**Comment by limuc** [comment]
@georgesnow no sorry, i don't use TOTP

@shad0whawk i can imagine! i'm sure it will be fixed

**Comment by shad0whawk** [comment]
I do use TOTP but I’m still using Authy for it. I did create one in my test database and the QuickType Autofill quits working after I set it up presumably because of the custom fields that are created. I removed those fields and it works again.

**Comment by shad0whawk** [comment]
What’s interesting is that items in the recycle bin with custom fields do not cause an issue. It’s only when I move them back out of the recycle bin that it quits working.

**Comment by georgesnow** [comment]
looks like you can add TOTP back in after the fact (through macOS not on my iOS device). and quick type still works. and if you have copy to clipboard that work too

**Comment by georgesnow** [comment]
recycle bin items must be flagged as "skip" or something

**Comment by shad0whawk** [comment]
Did you toggle the Stongbox QuickType Autofill toggle off/on after adding the TOTP settings to your entry?  I did that and it works until you refresh the QuickType database/file where it quits working.

**Comment by georgesnow** [comment]
no, i didn't. I left all those settings in place. I just added TOTP fields on my computer and iCloud sync'd the databases and it started showing on the Strongbox iOS app and autofill. I even added back the other database that i had working and now both populate the quick type.

i checked the caching and the times update and the quicktype still works

**Comment by georgesnow** [comment]
i wonder if there is a way to flag or use regex to only use custom fields that have URLs. I use custom fields for multiple URLs. ie system-a.google.com, system-b.google.com. 

At work we have all these subdomains half use one auth system and the other half use a different auth (so different passwords).

**Comment by shad0whawk** [comment]
Try toggling the QuickType Autofill on the Strongbox home screen and try again to see if it still works now that you added the custom fields back in.  My custom fields originated from Keepass.

**Comment by mmcguill** [comment]
Hi, wow, this is some great detective work... so it seems there is some issue with entries with custom fields I will need to investigate... Just popping a message on here to say thanks, I'll take a look into this very shortly. Regarding the Recycle Bin, yes, entries in here are deliberately skipped.

**Comment by shad0whawk** [comment]
I just downloaded 1.25.1 and the issue with custom fields preventing the QuickType from working has been fixed.  Thanks so much!  On a related note, when toggling the "Use QuickType Autofill" switch off, there's a momentary, subtle UI artifact where something occurs in the middle of the screen but doesn't render completely on the screen.

**Comment by mmcguill** [comment]
Glad to hear it @shad0whawk. The UI artifact is a progress spinner but obviously it's quite fast for your database and so disappears before it can fully render.

**Comment by georgesnow** [comment]
@mmcguill so there are still some types of custom fields that break on 1.25.1

TOTP  fields don’t break it, but I had 2 entries which I deleted at the same time and it fixed

one had a url.
Basic Entry was:
Username
Password
URL
https://email.work.com
with 1 custom field example:
URL-1
https://projects.work.com

And another had multiples, but no url in the entry. I didn’t have chance to add them back see which one broke when I do I will and report back.

**Comment by georgesnow** [comment]
So it’s an entry with custom fields and no url in the entry that breaksir

**Comment by shad0whawk** [comment]
Is Quicktype not working for that database as it did previously in 1.25, or is the Autofill options for entry not showing as you would expect?  I can’t seem to replicate your issue for either scenario. I modified an entry with a custom field to remove the URL. I also added a URL in a custom field that was similar to the main URL. I then toggled the main Autofill setting off/on in Strongbox and reopened the database. The QuickType works as expected for me.  The entry with a URL in the custom field shows an additional option to fill the username/password fields because the additional match.

**Comment by georgesnow** [comment]
If I add an entry that has a username and password, no URL, in this case 5 custom fields and QuickType is toggled or cache is updated on a database. then QuickType that was working for that database stops working. Move entry to trash and reset the cache or global QuickType in the app. QuickType starts working again for that specific database

**Comment by shad0whawk** [comment]
Hmm weird can’t seem to replicate it. I did exactly what you stated with adding a new entry with a username and password, no URL, and 5 custom fields in my test database and toggled the Autofill switch and all still works fine. My primary database has over 1000 entries—some with custom fields and no URLs—and it works fine since the last update.

I’m not discounting your experience/issue—just trying to help and give a second opinion.

**Comment by georgesnow** [comment]
Hmm No this is good. I want figure out what’s doing it. Did you title your custom fields? 2 titles have spaces not sure it matters. 

Yeah i have like 300 entries and all mixed

**Comment by georgesnow** [comment]
The entry is like this example:
Username: full name
Password: numbers 
Url: (blank)
Custom fields 
Expiry: 02/2023
expiry month: 02
expiry year: 2023
CVV: 123
I deleted the entry can’t rememver if I had one for the phone number

**Comment by shad0whawk** [comment]
I have the same setup with similar custom fields in my master database for credit/debit cards. I deleted the URL in a few of the entries and reset Autofill and it continues to work. My custom fields are mix case with spaces were appropriate.

**Comment by georgesnow** [comment]
Figured it out it’s the cache. Stale entry. So when I moved it back and the apps global QuickType is toggled the cache will say it updated and QuickType won’t work. I toggle the all 3 QuickType settings for this database and it works again.

**Comment by shad0whawk** [comment]
Oh good glad u figured it out

**Comment by mmcguill** [comment]
Thanks @georgesnow and @shad0whawk.

I've noticed that the cache can be a little temperamental at times while testing in Safari. I think this is just an iOS issue, as everything seems to go ok in the code.

@georgesnow I'm not sure there's much that can be done here, and so I think if you're reasonably happy or have no further suggestions, I'll close this issue off. Thoughts?

**Comment by georgesnow** [comment]
I am happy 😁thanks!

**Comment by mmcguill** [comment]
Great to hear it! 😀
