### ISSUE TITLE
App Not Available (App Store)

### ISSUE THREAD

**Issue by RichardFevrier** [mmcguill/Strongbox#24]
Hi, both of your apps (iOS / macOS) are not available in the french App Store.
Is there a reason ? Needs a translation ? 
It would be great to help our security here.
Thank you

**Comment by mmcguill** [comment]
Hi @RichardFevrier, 

Yes at the moment I'm waiting on a license from the French authorities before I can release in France. I applied back in November but I'm still awaiting a response. I'm hoping this will come through in the next week or so, and then I'll release in France. That is if everything goes ok with the regulator there. 

I'll pop a message back on here when I get it released. 

Merci!
-Mark

**Comment by RichardFevrier** [comment]
I look forward to using the app when it comes out in France.
Thank you for your answer.

**Comment by mmcguill** [comment]
Hi @RichardFevrier I believe it should be available for you now in the App Store in France but I have no easy way to check. Can you let me know?

**Comment by mmcguill** [comment]
Believe this is ok in France now.
