### ISSUE TITLE
No easy clearing of clipboard

### ISSUE THREAD

**Issue by UtXtiQArZE** [mmcguill/Strongbox#25]
there is no easy method of clearing the clipboard of the phone from the app.
once i've pasted in the password into the web page / app there is no way to clear the clipboard of the phone.

recommend clearing the clipboard during either the following.
1) after a set amount of time. e.g. 10 seconds.
2) after going back into the app
3) or a separate button on the app that clears the clipboard.

**Comment by mmcguill** [comment]
Yes, a good idea, I'll add to the Backlog

**Comment by mmcguill** [comment]
This is available now with 1.20.0
