### ISSUE TITLE
Remember which keyfile was used

### ISSUE THREAD

**Issue by MichiMunich** [mmcguill/Strongbox#26]
It would be great if the app could remember which keyfile was used to open a database. Currently it has to be selected again each time. If database and keyfile have the same name, the keyfile could also be used automatically.

**Comment by mmcguill** [comment]
Sounds like a good idea. I presume you would only want this in case where you also use a Password? 

For people who only use a Key File, this shouldn't be available, or should it just be a confirmation dialog? Might make it very easy to open the safe, but again this is an option.

Should also provide a master on/off config for this...

**Comment by MichiMunich** [comment]
Both constellations sound to me like a practical use case.

**Comment by bmsurber** [comment]
I’ve seen other apps that will auto-select a key file when it has the same name as the database but with a .key file extension

**Comment by mmcguill** [comment]
Auto detection of key file with same name now available with 1.23.0. Going to close this off for now. Feel free to re-open if this feature doesn't meet your needs.
