### ISSUE TITLE
Two Factor / OTP

### ISSUE THREAD

**Issue by mmcguill** [mmcguill/Strongbox#28]
It would be great if Strongbox could generate those OTP codes used for two factor authentication a la Google Authenticator...

QR Code support would be a bonus

**Comment by milesmcclane** [comment]
This would be a cool idea indeed

**Comment by mmcguill** [comment]
This has been implemented and released on iOS with 1.21.0. Let me give a brief description of how it works here.

You can add a TOTP code from the Edit Record screen. There is a TOTP/2FA button. This will give you a choice to scan a QR code with the camera, or enter the secret or OTPAuth url manually. Once the secret/otpauth url has been scanned or Strongbox should display the code. The code is visible in the Edit Record screen, the Browse screen, and the AutoFill screen. All of these locations are configurable on/off.

Strongbox uses KeePass custom fields (compatible with KeepassXC ("TOTP Seed" and "TOTP Settings" or the KeeOTP ("otp") plugin). If you already have these configured, Strongbox should just already work. 

If you enter an OTPAuth URL as the Password field, or anywhere in the Notes field (handy for Password Safe users) then Strongbox will automatically pick this up and display the TOTP code.

Any feedback welcome. 
-Mark

**Comment by mmcguill** [comment]
Seems to be working well...

**Comment by georgesnow** [comment]
On the iOS side would be possible to have the OTP copied to the clipboard when selecting a credential that has an OTP in its entry?

**Comment by mmcguill** [comment]
Yes, I think that's a good idea. I'll add an option for that!

**Comment by georgesnow** [comment]
tried the new version today works great!

**Comment by mmcguill** [comment]
Excellent!
