### ISSUE TITLE
webdav source not working

### ISSUE THREAD

**Issue by eike-f** [mmcguill/Strongbox#29]
I try to get syncing to work. I don't have itunes, as I use Linux. I also don't have dropbox or googledrive.

So I tried webdav with nextcloud.
I can connect and it actually shows me the contents of my folder but when i select the database file (a kdbx file), I get the error:

```
Error Reading Safe File
The operation couldn't be completed. 
(com.MattRajca.DAVKit.error error 404.)
```

googling it yielded nothing I could understand.

Can anyone help me? The information whether this is a bug in strongbox/nextcloud/webdav or a mistake of mine would also be appreciated.

**Comment by eike-f** [comment]
I guess [this](https://github.com/mattrajca/DAVKit/issues/12) is the issue.

Maybe its possible to switch to [this library](https://github.com/karelia/DAVKit)?

Bot look rather unmaintained but maybe the second one is working.

**Comment by mmcguill** [comment]
Hi @eike-f, definitely looks like an issue with the DAV library alright. I'll look into this, and check out your suggested replacement shortly, might be an easy switch/replacement. 
Cheers,
-Mark

**Comment by mmcguill** [comment]
Hi @eike-f, unfortunately not a drop in replacement, looks like I'll have to dig in more and find out whats wrong, something to do with authentication challenges for sure.

**Comment by mmcguill** [comment]
Hi,

With 1.21.2, WebDAV should be working, I've tested against Nextcloud and that seems to be fine, but would be interested to hear your experiences. Will leave issue open for a while...

-Mark

**Comment by eike-f** [comment]
Thanks!
Webdav itself works like a charm.
But I had some trouble in filling out the form. Maybe not worth debugging, your call:
When I used the password autofill to fill out username and password for the webdav, the first time I couldn't press connect afterwards and had to kill strongbox. If you would like further testing, I can do that.

**Comment by mmcguill** [comment]
Thanks @eike-f, I'll have a look into that
