### ISSUE TITLE
syncing over files app with nextcloud yields error

### ISSUE THREAD

**Issue by eike-f** [mmcguill/Strongbox#30]
I would like to get automatic sync in place.
One way I tried was choosing sync over files and choosing a file in my nextcloud folder.
I selected "edit in place".

When now the file is changed in nextcloud, i get the error

```
There was a problem opening the safe.
The file doesn't exist.
```

instead of automatic sync.

Should I instead use "make a copy"?
But then I guess no automatic syncing would take place.

**Comment by eike-f** [comment]
It now works with "edit in place".
I'm at a loss what happened, unless the latest release bugfix concerning icloud fixed this issue on the fly.
If thats the case, thanks for reacting so fast!

**Comment by mmcguill** [comment]
I don't think it was related to the iCloud fix, but could have something to do with the download status of the file in the Files app, perhaps it hadn't been fully sync'd yet before you added it to Strongbox?

**Comment by eike-f** [comment]
I dont think so. I tried it multiple times and could always open the database after adding it to strongbox. Only after it had been changed elsewhere the error came. And i had waited for the nextcloud sync.
