### ISSUE TITLE
App password bug report:

### ISSUE THREAD

**Issue by eike-f** [mmcguill/Strongbox#31]
I like the app password very much but there is a bug with it:
Summary:
It can happen that app locking is disabled until the app is killed and restarted.

Steps to reproduce:
(0. enable app PIN)
1. Kill the app (press home twice in quick succession and push strongbox out of the top of your screen.
2. Start strongbox
3. Press on a safe to open it.
4. While on the password insert dialog for your safe, leave the app.
5. Now entering the app does not need your PIN code anymore, no matter from where you leave it, until you kill the app again (see step 1).

further comments:
This seems to be a problem for all input dialogs, it also works with the change password dialog within a safe.

**Comment by eike-f** [comment]
@mmcguill : You're very welcome! Thanks for your work!
Actually I only now realized that the individual passwordsafe pins are almost exactly like I like them and make in my opinion the app password superfluous. So from user perspective maybe the easiest and best way is to get rid of the app pin, because with safe pins there doesn't seem to be such a problem.
A nice feature of this solution is also that your energy can be used to make the password pin secure and not be distributed.

**Comment by mmcguill** [comment]
Hi @eike-f, I'm afraid I've had to disable the Top Level App Privacy lock. I've received a lot of complaints about it interfering with dialogs, in particular with Storage Provider logins. This on top of the bug you've reported here has convinced me that I need to rethink the design of the app level lock. As you've said yourself, it becomes kind of secondary with the convenience pins. I'll close this issue off for now, and we can readdress the whole top level lock at another juncture.
