### ISSUE TITLE
Synology Drive not shown in Files app

### ISSUE THREAD

**Issue by seisure** [mmcguill/Strongbox#33]
When opening an existing database via the ios files app, the Synology Drive app is not shown. Other apps like iCloud or Owncloud are visible. When I open the Files app directly or via another app like whatsapp then the Synology Drive app is visible as storage location.
At first this does not sound like an issue for your software, but I could retrace that the Synology Drive app is shown in other context.

It would be nice if you could come up with a solution.

https://itunes.apple.com/app/synology-drive/id1267275421
https://www.synology.com/en-global/dsm/feature/drive

**Comment by georgesnow** [comment]
My understanding of synology drive is more like WebDAV and not a sync. If you use the DS cloud app it will show in strongbox. The DS Cloud app actually locally syncs the file as oppose to “viewing” it remotely from the NAS. Just a suggestion

**Comment by mmcguill** [comment]
Hi @seisure, I believe this is because the Synology app does not support "Editing in Place" via the Files app. For example if you make a change to a File on the Synology Drive in the Files app on your iPhone, does it get sync'd back out to Synology? I could try have a closer look at whats happening here, but it's difficult without running my own Synology server setup.

**Comment by georgesnow** [comment]
I should clarify. when referred to synology drive above i meant. the "Synology Drive" app. The drive app is only a "viewer". You can tell it to download the file to your device, but if the "Editing in Place" is required it won't work and Synology based on the forums doesn't look to be supporting it.

The "DS Cloud" app connects to the NAS drive and you can specify to locally sync folders or files onto the iOS device. The DS Cloud seems to support "Editing in Place". In my basic test Strongbox shows DS Cloud as available option to pick a safe from. 

Note: I haven't tested KeePass or Password Safe file from there. I would recommend use a dummy safe first.

**Comment by mmcguill** [comment]
Going to close this off for now. Not sure there's much I can do here. 
-Mark
