### ISSUE TITLE
Custom order not supported?

### ISSUE THREAD

**Issue by milesmcclane** [mmcguill/Strongbox#36]
If I change the order of folders via another Keepass app, Strongbox displays them in standard alphabetic order, subsequently syncs back to database in this order. Is there a way to just honour the order it’s imported in?

**Comment by mmcguill** [comment]
Sounds like a fair request. Added to the backlog.

**Comment by milesmcclane** [comment]
Great thanks :)

**Comment by mmcguill** [comment]
This should be available for you now with 1.21.2 and 1.4.3 (Mac). There is a new Setting in Preferences for this:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/344791/51979500-9593f080-248d-11e9-8e32-9202e56bd3e3.png">

Be glad to hear if it's working for you. -Mark

**Comment by iron77** [comment]
Good at my end!
@milesmcclane ?

**Comment by milesmcclane** [comment]
Haven’t been able to test it as I have been away from my main machine for sometime! Stuck with iOS devices and I don’t have a Keepass app that allows me to alter the order of the database natively. 
I’ll try it out after the weekend!

**Comment by milesmcclane** [comment]
Potentially something that could be also added in Strongbox?

**Comment by mmcguill** [comment]
Yeah, straightforward enough task, I'll add an issue for it.

**Comment by milesmcclane** [comment]
Great!

**Comment by milesmcclane** [comment]
FYI, this works great for me after testing.

**Comment by mmcguill** [comment]
Great, I'll close off now, as I think this is fine.
-Mark
