### ISSUE TITLE
Keepass2 Kdbx file not valid

### ISSUE THREAD

**Issue by claystation** [mmcguill/Strongbox#37]
Hi,

I am trying to open my Keepass2 KDBX file in the app on an iphone. When i try to open it, the app gives me an error saying it is not a valid safe file.

I checked in my Keepass on the computer and it has AES/Rijndael 256 bit encryption (I cannot choose anything else). But i also think AES 256 is within the normal range of AES encryption.

I get no further information about what is wrong. It is just a MyKeys.kdbx file. Any other suggestions on how to fix this? 

**Edit:** I tried creating a Keepass 2 Classic safe in the app. I synced it to my computer and tried to open it there. No problem at all. Everything works fine. It has the same encryption but 100 times more rounds. I edited the amount of rounds to the same number as the DB created by strongbox. Same error.

**Comment by mmcguill** [comment]
HI @claystation, what client are you using other than Strongbox and on what platform (Windows/Linux/Mac)?

**Comment by mmcguill** [comment]
Ok, something about the file that Strongbox doesn't like. Is there anymore detail other than "Not a valid safe file"?

**Comment by claystation** [comment]
It just says: 

Invalid Safe File
This is not a valid safe file!

Nothing else.

**Comment by mmcguill** [comment]
Ok, this is very likely because you're safe has a "KeePass 2.x pre-release (alpha & beta) : 0xB54BFB66" header. I'll add some code to give a better description of the problem. But do you happen know if your safe was created with an older pre-release or alpha/beta version of KeePass?

**Comment by claystation** [comment]
I just upgraded the Keepass version on my Linux machine to 2.40 so I can't check back but i believe it stated (dev) after the version number 2.32. So it might have been created by a dev/pre release version. I don't exactly know. Is there any way i can check and otherwise change it? Or is it better to create a new database and import my entries from the old one and replace it eventually?

**Comment by mmcguill** [comment]
I'm not sure what way the KeePass client will do things, but does say Adding a new entry and saving the database with the new KeePass (release version) help? Or with official Windows KeePass (release) client?

**Comment by claystation** [comment]
I tried multiple times to save the database with the new version. Not with a new entry. But that didn't help. What i did now is create a new Database file (with the newer version of keepass2) and import all my entries into that database. It is working now, on my iphone and ubuntu machine. I dont know about my Windows machine as i can't access it right now and my android is going out of usage (transferring to iphone for now). So i guess this may be closed but in my opinion the error message should be more clear. 

Thanks for the help anyway :+1: !

**Comment by mmcguill** [comment]
Definitely need to make the error message a bit clearer here. Very glad it's working for you now... Cheers!
