### ISSUE TITLE
Issue with Folder and Entry Level Edit Function

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#38]
Selecting a folder entry using the radio buttons doesn’t persist for a single folder or multiple folders. If the user selects the folder, the program deselects the folder.  

Steps to recreate issue:
1. Open safe
2. Select Edit
3. Tap radio button for a folder (radio button fills with a check mark then empties within a second)
4. Tap again with same result
5. Tap multiple entries and both fill and the empty in the order of my selections

I’m still able to use the Move and Delete functionality if I select the folder and subsequent option quick enough. This appears to be an issue in the latest update because I tried the previous version on my other phone and it works as expected. I updated that phone and experience the same issue on it as well. 

Not sure if it matters, but I’m on an iPhone XS Max running 12.1.3.

**Comment by mmcguill** [comment]
Thank for the report @shad0whawk, can confirm the issue is only on 1.21.0 and is related to TOTP feature. Should be a quick fix.

**Comment by shad0whawk** [comment]
Thanks for the quick fix!  I'll close this one.
