### ISSUE TITLE
Bug Report: Convenience pin for system passwords

### ISSUE THREAD

**Issue by eike-f** [mmcguill/Strongbox#39]
Overview:
Its impossible to autofill system passwords (like icloud pw) if convenience pin is activated.

Steps to eproduce:

1. go to system controls
2. try to change your icloud password and hit the autocomplete button (named passwords? I have german ios...)
3. strongbox asks for convenience pin but no confirmation button is there.

Comments:
Maybe the pin input can be done with the same tool as the master credentials, as they work here

**Comment by mmcguill** [comment]
Thanks @eike-f, this is strange indeed, it looks like the top keyboard bar gets removed by the system somehow, leaving the user stranded. Not a great experience. I'll look into this shortly

**Comment by milesmcclane** [comment]
I can’t even get auto fill to work in any situation or any combination of pins Touch ID or even the master credentials. Just returns back to an empty screen. 

Any suggestions on what’s going on here?

I’m interested to see how strongbox would cope with autofilling a password design such as protonmail; 
ie: main password - totp code - inbox password

**Comment by mmcguill** [comment]
Hi @milesmcclane, that's odd, could you give me more details (perhaps mail me, to keep this thread clean). You should be able to use autofill.

**Comment by mmcguill** [comment]
This should be fixed for you @eike-f, moved away from a Keyboard accessory 'OK' button to a built in View Based one which should work on all system dialogs. Closing this one out, feel free to re-open if it is still an issue.

**Comment by eike-f** [comment]
Cool, thanks a lot!
By the way: when accessing a safe from autofill, there is no spinning symbol while decrypting. I don’t think its worth the hassle of fixing but thought you should know.

**Comment by mmcguill** [comment]
Yeah, aware of that issue, basic SVProgressHUD library doesn't seem to work well in App Extensions.
