### ISSUE TITLE
Design request: protect app settings with password

### ISSUE THREAD

**Issue by eike-fokken** [mmcguill/Strongbox#40]
A possible attack may be this:
1. Your „friend“ gets hold of your phone goes to strongbox and sets „autolock database“ from „immediately“ to „never“.
2. she hands it back and asks you to log into some account for whatever madeup reason.
3. she gets hold of your phone again and goes to the safe which is still open

Possible solutions:
1. make database autolocking a „per safe“ setting that is changed inside the safe.
Or
2. protect all app settings by a password.

I like the second better, because it is safer. If it has the same input screen as the master credentials, i could even enter the password with autocomplete and have the password in my safe.

**Comment by shad0whawk** [comment]
I agree this is a security risk based on the current design.  So either the app-level authentication mechanism would have to be added back, or this setting would have to be migrated from a global setting to a database-specific setting which would allow different auto-lock times for each database.

**Comment by mmcguill** [comment]
Yeah, it seems like the best way to mitigate this kind of scenario is an App lock. Just need to get a better design than the last implementation, as the various storage providers tend not to play well with any top level view/navigation interference (they assume they own the view hierarchy).

**Comment by Mukrosz** [comment]
I am a few months late but I second this request.
All security, privacy apps MUST have this feature (protonmail, minikeepass, authy to name a few)
Most apps allow you to secure the app with a touchID/FaceID but what good is it if it is the same authentication method as what you use to unlock your phone? There are so many cases where a second layer password is needed for the whole app.

Cheers!

**Comment by mmcguill** [comment]
Settings/Preferences can now be protected with 1.28.0. Leaving open for comments for a short while.

**Comment by shad0whawk** [comment]
Thanks for the adding this feature. I like the addition of this extra layer of security. It works well so far for me with no issues.

**Comment by mmcguill** [comment]
This looks good now... closing...
