### ISSUE TITLE
Feature request: allow choice of separator for Dice Word style passcodes

### ISSUE THREAD

**Issue by milesmcclane** [mmcguill/Strongbox#43]
Most other Keepass apps offer this distinction. I like to try to keep consistant with this type of password (as they’re made for remembering). Would be handy to choose my own separator to be consistant with previous passphrases.

**Comment by shad0whawk** [comment]
Allowing us to add/choose a separator value would be nice tweak.  Also, there's a word count .but would it be possible to apply the character limit to the overall length of the words since some websites have a relatively short character limitation such as 20 characters?

**Comment by milesmcclane** [comment]
Just wanted to bump this to see if you had any further thoughts on it? 

Most of my existing diceword passwords are of the same format and separator, would be great to be able to match the style I already use in the generation settings. Only because these sorts of passwords are made to be easier to remember, so it’s logical to be able to set your own separators etc.

**Comment by mmcguill** [comment]
Yes, sounds good, just a matter of prioritisation... you wanted to choose number of words and then a simple single character separator like '-' or something like that?

**Comment by milesmcclane** [comment]
Ah yes i fully understand! Probably a niche case, and I definitely get the need to prioritise other more fundamental and frankly important aspects of the app. 

In order to fit in with my practices, I would like to be able to choose the amount of words, to have all letters lowercase, and have a simple space separator. But that’s because that’s how I use these passwords. Nice and easy to type.

It certainly would be nice to be able to choose the separator though I’m sure! 

Thanks for following up.

**Comment by mmcguill** [comment]
Cool, yes, will do my best to get this in shortly for you! :)

**Comment by milesmcclane** [comment]
Great news! Thanks :)

**Comment by mmcguill** [comment]
Should be there for you in 1.27.2 @milesmcclane 

Let me know if all ok!
