### ISSUE TITLE
KDBX 4 database with password and key needed to encrypt leads to error "unknwon cipher"

### ISSUE THREAD

**Issue by MelBourbon** [mmcguill/Strongbox#45]
I have created a Keepass Database with KeepassXC on Windows using KDBX 4.0 format, Twofish: 256-bit and Argon2 as key derivation. The database needs a password and a keyfile (*.key) for encryption. This works flawless in KeepassXC 2.3.3 on Windows 10 and Keepass2Android 1.06f on Android 8. But on iOS 12.1.1 I get the error message "unknown cipher". Is strongbox not compatible with the choosen setting of the Keepass Database? Because in the description is written it works with Twofish and Argon2.

**Comment by mmcguill** [comment]
Hi @MelBourbon, should be! Could you post the full Error message or a screenshot of it? It should have a UUID in it I believe.

**Comment by MelBourbon** [comment]
Hi @mmcguill I changed the algo to ChaCha20: 256-bit and it worked. To crate the error message again I changed back to Twofish again and still works. Sorry, seems to be my fault. Issue can be closed.

**Comment by mmcguill** [comment]
No worries at all!
