### ISSUE TITLE
A thought on notes.

### ISSUE THREAD

**Issue by milesmcclane** [mmcguill/Strongbox#47]
I have already mentioned my desire to have the note section of an entry selectable in a standard iOS manner, rather than just copying the whole note as it is now, but I have a further suggestion that might prove extremely useful.

To use an analogy, I'm often in a situation where I have a piece of paper that I would like to put in my safe. My partners banking details - for example. 2FA codes, things like that.
These thing don't really fit into the standard entry page, at least in a useable way.

Would it be possible to add the ability to create an entry that is purely a note, purely a 'sheet of paper'?  
I think this would be invaluable, though I admit my use case could be niche. 
I currently use standard notes for this type of thing, but I would love to be able to consolidate this into my main and most trusted password and document vault.

**Comment by shad0whawk** [comment]
I'm able to easily select and copy specific text within a Keepass note without enabling Edit mode.  Is that what you're trying to achieve or is it something else?

**Comment by milesmcclane** [comment]
Actually, so am I! Has this behaviour changed? Or else I might have got myself confused with which app is which as I’m testing keepassium as well. My bad if that’s the case. Oops! 
I still like my other general idea though. 
I’ll try to edit the above comment to reflect my stupidity!!

**Comment by Ben-Voris** [comment]
I use notes to hold other bits of signin information.  I am able to select a word at a time.
