### ISSUE TITLE
Strange behaviour when using safe from Files

### ISSUE THREAD

**Issue by Gretsch13** [mmcguill/Strongbox#48]
I have observed a strange behavior when using a safe from the Files app. When I update the safe on my Mac and sync it via iCloud Files, the App wont open the updated safe. Instead a copy appears in my Files app. 
Steps to reproduce: 

1. I have a safe called 'example.kdbx' in iCloud Files and open it with Strongbox on my iPhone with the option to open in place.
2. Now I close Strongbox and push an updated version of the safe from my Mac.
3. When opening the safe in Strongbox again, it displayes the old version of the safe (maybe cached?)
4. In my Files app there is a second safe now, called 'example 2.kdbx'. This seems to be the file cached by Strongbox, because when I delete this file, Strongbox shows me, that the safe 'example.kdbx' does not exist, when I try to open it.
5. Now I have to remove the link to the old file and reopen the file 'example.kdbx' again.

Would be helpfull, when Strongbox would automatically detect the updated safe.

**Comment by mmcguill** [comment]
Hi @Gretsch13, thanks for the report. There definitely does seem to be a little bit of sync-ing trouble with files opened/referenced as "Edit in Place" through the Files app. I'm not sure if there's much Strongbox can do about it at the moment, as some of the trouble seems to be with Apple's sync-ing side of things, and the links ("bookmark" is the technical term) it uses to track external Files files.

Could I ask what client you are using on the Mac to make changes?

Also, you can almost certainly get a better experience if you were to use the Native iCloud 'Strongbox' folder (which means Strongbox doesn't need to use "Bookmarks" to keep track of external files. Is this an option for you?

Thanks,
-Mark

**Comment by Gretsch13** [comment]
Hi @mmcguill, thanks for the quick response.
On my Computers I use KeePass XC for editing the .kdbx-Files. I tested the sync over Files, because in the future I want to sync with Nextcloud. For the moment I can use the integrated iCloud.

-Steffen

**Comment by mmcguill** [comment]
Ok, you can also use WebDAV for a very good (immediate sync) with Nextcloud, I know a few people are already doing that, and I've tested it myself, it seems to work well.

**Comment by Gretsch13** [comment]
Okay, I will try that. Thanks. Since you say that you can't solve the problems from your side (probably), I will close this thread for now.

**Comment by mmcguill** [comment]
Ok, thanks @Gretsch13
