### ISSUE TITLE
Possible Minor UI Issue/Inconsistency...

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#49]
...almost not worth opening an issue ticket especially since I don't know if this intended design or not.  

When I'm in an entry within a safe, the back indicator initially shows "<".  If I select "Edit", the top bar changes to "Cancel" followed by the entry name ready to be edited.  If I select "Cancel" without making any changes and revert back to the previous screen, the "<" now shows "< B..k".  In the edit screen, If I make a change and select "Done", it appears as previous "<".

**Comment by mmcguill** [comment]
No problem, I'll take a look, sounds like an easy fix.

**Comment by shad0whawk** [comment]
Looks to be fixed now. Thanks!
