### ISSUE TITLE
Feature request: exclude files from backup

### ISSUE THREAD

**Issue by dbluxo** [mmcguill/Strongbox#51]
It would be nice if I could (optionally) exclude my files (keyfiles and safes) from backup.

**Comment by mmcguill** [comment]
Hi @dbluxo, so at the moment, all Strongbox local files (Documents and Application Support) files are excluded explicitly from backups. I'm not sure it's a good idea even to make this optional, I think I'd prefer to leave safe storage, and key file backups in the hands of the user, i.e. they manually choose where/when/how to store these very private files.
Hope that helps,
-Mark

**Comment by dbluxo** [comment]
I‘m fine with that. I thought these files will be included per default without any chance to exclude them.
