### ISSUE TITLE
Editing Attached Text Files

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#52]
I have some entries with text files attached. I can open them in Strongbox and select the text to copy, but I can’t seem to edit them. Is it possible to add this ability in a future release?

**Comment by mmcguill** [comment]
It's definitely possible @shad0whawk, I'll add to list, but it probably doesn't take super high priority, given the alternatives, e.g. notes field, custom fields, and the ability to open, copy and re-add a text file.

**Comment by shad0whawk** [comment]
I appreciate it and I understand your position. I ran into this scenario yesterday when I was trying to edit an attached text file that contains some data that I could put in the notes field but prefer to keep it in the attachment instead.
