### ISSUE TITLE
WebDAV setup freezes when inserting credentials

### ISSUE THREAD

**Issue by eike-fokken** [mmcguill/Strongbox#55]
Hey, I think I pinpointed the exact issue now:
Summary: can’t insert webdav credentials from another safe in strongbox, as then the connect button is unresponsive.

Steps to reproduce:
Set up a webdav safe, hit the autofil button („passwords“), try to press connect button

I think, the problem also triggers when leaving strongbox during webdav setup (e.g. for copying the webdav url)

**Comment by mmcguill** [comment]
Ok, thanks for the report @eike-f. Noted.

**Comment by mmcguill** [comment]
I believe this is fixed now @eike-fokken - Are you still experiencing trouble?

**Comment by eike-fokken** [comment]
The issue is indeed fixed, thank you! A minor problem remains: leaving the webdav prompt e.g. to get the url, cancels the setup, therefore one needs to copy the url beforehand. This is probably not a big issue, just wanted to let you know.

**Comment by mmcguill** [comment]
Got it thanks @eike-fokken - I'll have a look at that cancellation issue shortly...
