### ISSUE TITLE
Allow Selecting Key File from iOS Photos App

### ISSUE THREAD

**Issue by mmcguill** [mmcguill/Strongbox#59]
Handy to be able to select one of your photos as the key instead of having to access it via the Files app.

**Comment by jmichael2497** [comment]
may be excess caution, but maybe add usage recommendations in faq on how to do this properly.

just like with written passwords... probably not a good idea to use pictures of your pet, spouse, kids, birthdays, hehe? (although depending on the number of pics on a phone, i suppose it could be needle in a haystack, security through obscurity.)

seriously though, pictures don't seem like very good files to use unless they're read only. i've come across too many dumb "automagic" apps that alter metadata "for your convenience" like EXIF, id3, doc owner tags, etc, which would break the file as key.

i'm still trying to figure out if there is a reliable way to use this.

**Comment by mmcguill** [comment]
Good points, noted. This was a feature request from a support email from someone who uses a photo as his key file but for sure there are some gotchas there.

**Comment by mmcguill** [comment]
I've implemented this now. I think it's probably on the user to ensure their photo file does not get altered in anyway. But I'll add a little something to the FAQ on this.
