### ISSUE TITLE
Purchase not as smooth as could be

### ISSUE THREAD

**Issue by eike-fokken** [mmcguill/Strongbox#63]
Summary: Purchase works but it doesnt look like it.

What it does: After hitting buy and entering appleid password, the app keeps saying „purchasing“ and having this spinning symbol in the middle of the screen, probably forever. Only after hitting the trial version bar at the bottom of the screen, the app realizes that pro is already purchased.

In the end no big deal, but felt strange, as i wasn’t sure the purchase had actually worked.

**Comment by mmcguill** [comment]
Agreed, I get an email every now and then about this but have not been able to successfully debug it...

**Comment by mmcguill** [comment]
@eike-fokken I believe purchasing has improving significantly over the last few months. Can we close this one off?

**Comment by eike-fokken** [comment]
Go ahead, I’ll take your word on this. But naturally I can’t test it, having purchased already.

**Comment by mmcguill** [comment]
Thanks @eike-fokken - Appreciate the support too
