### ISSUE TITLE
Bug report: Webdav safe not working for system passwords 

### ISSUE THREAD

**Issue by eike-f** [mmcguill/Strongbox#64]
Summary: You can’t enter system passwords from a webdav safe via autofill.

Steps to reproduce:
0. Make sure you have your iCloud password 
1. Enter settings
2. Hit your apple id (topmost option)
3. Scroll down and press sign out or similar (I have german ios)
4. When prompted for your iCloud password, press “passwords” and hit a webdav connected safe.

Result: strongbox claims an ssl error, although it works fine if the safe is opened directly from the app.

Maybe important factor: the webdav server is tls 1.2 only

Could also be that this is a bug on apples side.

**Comment by eike-f** [comment]
I just realized that this happens for every password, not obly for system passwords!
I‘m no expert but my guess now is that it is connected to the tls 1.2 only constraint I mentioned, as this started occurring after i switched my cloud server to a new server that offers only this tls version.

**Comment by mmcguill** [comment]
Thanks @eike-f, could you post a screenshot of the error please (if it's not confidential?)

**Comment by eike-f** [comment]
![img_0824](https://user-images.githubusercontent.com/33839210/53292637-b66a1000-37c5-11e9-82de-8d5c0ce9c370.PNG)
There you go

**Comment by mmcguill** [comment]
And to be clear, this is only in the AutoFill context, it works fine from the App?

**Comment by eike-f** [comment]
Exactly

**Comment by mmcguill** [comment]
This might be to do with the App Extension's ATS setting, I'll try a different setting in the next release and hopefully that will work. Expect that in the next day or two.

**Comment by eike-f** [comment]
Cool, thanks!
I really like your app and how you're handling feedback!

**Comment by shad0whawk** [comment]
I agree!

**Comment by mmcguill** [comment]
Thanks @eike-f and @shad0whawk 😀 

This change should be available for you now to test, with version 1.22.0 from the App Store. Could you let me know if it fixes things for you?

**Comment by eike-f** [comment]
Works fine, thanks!
