### ISSUE TITLE
file naming and replacement

### ISSUE THREAD

**Issue by TBugReporter** [mmcguill/Strongbox#66]
I keep a .kdbx in Dropbox, and copy it over to Stongbox every time I open it, to propagate whatever changes I may have made to it elsewhere.  However, other KeePass compatible iPhone apps simply overwrite the matching file in their file repository.  Your app refuses to overwrite the existing file, and (probably because of this) always asks for a new filename (providing no default answer to this question).  I wish yours were like the others in this respect, or at least used the existing name as a basis for a new one.

**Comment by shad0whawk** [comment]
Yeah I noticed this too when I tried to copy in an updated version of my database. This functionality would be useful if you don’t want to link directly to a database in a cloud service and simply want to overwrite (update) an existing database with a newer version. I know you can make those read only but it still has to go out and retrieve it each time.

**Comment by TBugReporter** [comment]
I wouldn't want to overwrite the cloud version with Strongbox's until it has KeePass's sync capability, because the cloud version may have changes that never made it to Strongbox.  (I treat all the KeePass-compatible iPhone apps as if they were read-only because of this.)

**Comment by shad0whawk** [comment]
When I was using MiniKeePass, I would select the latest version of my database hosted on a cloud service and open it with MK. It would overwrite the existing database (assuming it was the same one) and keep the existing credentials. I wouldn’t have to renter the master password because it was the same database with a few additional changes since the last copy.

**Comment by TBugReporter** [comment]
Interesting - I was never able to skip the master password, but then I always close the file when I'm done with it, in case someone else gets a hold of the phone when I'm not looking.

**Comment by TBugReporter** [comment]
Okay, here's a question that's only semi-related to this ticket, but I don't think its significant enough to start a new ticket for.  I've been making numerous small changes to my database ("safe", in Strongbox terminology) and comparing exporting from the Dropbox app vs. importing with the Strongbox app, and I can't figure out how, or if there's a way, to force Strongbox to reread the file from Dropbox.  I currently have two copies of the file in Strongbox, but the one showing the Dropbox icon is out of date, which is why I went back to the Dropbox app to recopy it (which again insisted on my picking a new name for it).

**Comment by mmcguill** [comment]
Hi there,

Just trying to narrow down your usage. Could you describe for me what the following mean and how I would do them:

1. "exporting from the Dropbox app" 
2. "importing with the Strongbox app"
3. "copy it over to Strongbox"

Are 2 and 3 the same? I take it you are not using iTunes File Sharing, or are you? Is it via the Files app?

Let me know and I'll try get to the bottom of this. I'd imagine I'm just being a little over cautious and deciding not to overwrite anything, but I need to know the scenario here, as iTunes File Sharing is very different from import from Files/URL. 

In fact, while I think of it, iTunes File Sharing might be exactly what you want, local copy that overwrites based on file name. Have you tried this?

**Comment by shad0whawk** [comment]
My current setup links my primary database directly to OneDrive as read-only. From my own experience and previous use case when I was using MiniKeePass, I used to go to my cloud service app and select its version of “Open With” and then select MiniKeePass. It would then copy in the new database and overwrite the old one if it was the same database (presumably based on name). I wouldn’t have to create a new name and go through the setup process. It would also unlock automatically using Touch ID without having to renewer the master password after the update. If I try to do the same process in Strongbox, it doesn’t automatically overwrite/update the existing database if they’re the same. The first step is to create a unique name so I’d have to delete the existing copy and set the updated one up as a new instance. I think that’s where TBugReporter was going with it.

**Comment by TBugReporter** [comment]
Yes, shad0whawk's description is pretty similar to what I do/did with MiniKeePass or KeePassTouch.  As you know, each app on iOS has its own separate file storage area as a security precaution, and there are restrictions on when and how a file can be transferred from one app to another.  AFAICT, there are three ways to get a pre-existing cloud-shared database into Strongbox:

1. Open the other app that currently has access to the file (in my case, Dropbox) and use that app's tools to copy or "export" the file to Strongbox;
2. Open Strongbox and "Add an Existing Safe" | "Strongbox Local & Cloud"; or
3. (I hadn't thought of this until you mentioned it) Use iTunes on a PC or Mac to transfer the file.  (This is not an option for me, because while I do have iTunes installed on a PC and configured to connect with my iPhone, generally the times I use Strongbox are when I'm *not* near that PC; and when I said about "copy[ing] it over to Strongbox", I was referring in general to either 1. or 2. - whichever is more convenient for a person at a given time.)

As you suggest, IMO you're being overly cautious in deciding never to overwrite files (rather than leaving that decision to the user), but you're also causing inconvenience by not using an existing file's name as the basis for a new name when a file by that name already exists in Strongbox's storage area.

**Comment by mmcguill** [comment]
Got it. Will look into this for you. Possibly easiest way is to ask user if they want to overwrite or keep both, that way it remains safe but you also get the behaviour you seek.

**Comment by shad0whawk** [comment]
That makes sense. Ideally the program should prompt this automatically if the database being imported/copied has the same name/attributes as an existing database already linked as a copy. This would avoid having the user specify the name.

**Comment by shad0whawk** [comment]
I'm using v1.23.0 and I like how Strongbox prompts me to either update or create new when I try to add an existing safe to Strongbox from another application.  I also don't have to reenter my master password if I have Face/Touch ID enable.  Thanks!

**Comment by mmcguill** [comment]
Glad you like it @shad0whawk ! That was what I was aiming for... Are you having any trouble with importing your databases at all? I have an issue #71 at the moment, and I'm trying to get to the bottom of it, so it would be good to know if you're working ok on 1.23.0

**Comment by shad0whawk** [comment]
I do have a weird issue along those lines.  In this particular use case, I am using Synqion as my cloud service and import host.  I can import the database on my iPhone 8 from the Synqion app using the "Open with" functionality and it shows up with a tablet/phone icon.  Then I can repeat the process and it prompts me to update or create new.  If I do the exact same process on my XS Max, it attaches it with a blue icon with a cloud outline and won't prompt me to update or create on subsequent "Open with".

**Comment by mmcguill** [comment]
Ah yes, that'll be because you have iCloud turned on on the XS Max. If iCloud is turned on, it assumes you do not need the traditional local file importation sequence/setup. Generally iCloud users will be assumed to want less techie features, and things to just work without manual synchronization etc.

**Comment by shad0whawk** [comment]
That makes sense since iCloud is disabled on the iPhone 8.  How would I get around this on my XS Max so that I can copy in the database and then overwrite it in future copy ins?

**Comment by mmcguill** [comment]
Just go to Strongbox Settings (little gear icon in top right of main screen), and turn 'Use iCloud' off. That should do the trick.

**Comment by shad0whawk** [comment]
Ah well that works perfectly now.  Thanks!

**Comment by mmcguill** [comment]
@TBugReporter this should be working for you as expected now with 1.23.0. I'll leave open for a few days, just in case you have any feedback.
