### ISSUE TITLE
Issue with Cancelling New Entry

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#67]
The cancel button in a new entry doesn’t appear to work correctly (or at least as I would expect it to). If I create a new entry in a database and press “cancel” prior to the initial save, the application returns me to the previous screen where the cancelled entry exists in the list where I then have to manually delete it. This exhibits the same exact behavior as if I had pressed “save” in the new entry screen for the first time. I would expect the new entry to be cancelled and deleted if I had not saved it at least once to establish the entry within the database.

**Comment by mmcguill** [comment]
Noted, should be fixed with next release in the next day or two.

**Comment by shad0whawk** [comment]
Thanks for the fix!
