### ISSUE TITLE
[iOS] KeePass Database Import Broken

### ISSUE THREAD

**Issue by agireud** [mmcguill/Strongbox#71]
Release of version 1.23.0 on iOS has broken support for KeePass database imports.

**Comment by mmcguill** [comment]
Hi @agireud, 

Any further information? Could you tell me the steps you are using and what you see happening?

Thanks,
-Mark

**Comment by agireud** [comment]
Using either the "Copy to Strongbox" feature from a seperate app or the "Add Existing Database" feature from within the app produces the same results.  Here is a screenshot of the output:

![img_0043](https://user-images.githubusercontent.com/6656150/53832647-57866280-3f4c-11e9-95dd-1796b19ece78.PNG)

**Comment by mmcguill** [comment]
Thanks for the extra info. A few more questions:

1) Do you mind if I ask where you are importing from/which app?

2) There's no way you're using a beta version of another KeePass client somewhere else with this file is there? 

3) And you're definitely selecting an actual KDBX file for import? 

Sorry if that seems like a silly question. Basically the above message indicates that Strongbox is not able to read the initial first few bytes that tell it what kind of database it is, and if it's valid.

**Comment by agireud** [comment]
@mmcguill 

1. I have tried importing from both the native ios Files app and using Synology Drive (both saving to Files and using "Copy to Strongbox".  Neither have received any updates and were working fine until today.)

2. No, I use the KeePassXC client on other devices but it has not been updated recently.  (Only your application has received an update and all the others continue to work without issue.)

3. Yes, it should be noted that I have a key file with the same name prefix and the .key extension in the same Strongbox document folder (local, on my iPhone).  The KDBX file continues to work with all other clients.

**Comment by mmcguill** [comment]
Thanks. Could you tell me the name of the file (does it have any non ascii characters/spacing?), feel free to email me support@strongboxsafe.com if you'd like to take offline

**Comment by agireud** [comment]
@mmcguill The file names are of the form `PassVault.kdbx` and `PassVault.key`

**Comment by mmcguill** [comment]
Cheers... Ok, do you have access to a Mac/Linux box that you could run the following for me on that file:

On a Mac:
od -t x1 -N 8 PassVault.kdbx

On Linux:
od --format=x1 --read-bytes=8 PassVault.kdbx

If you could run that and let me know if you see:
0000000    03  d9  a2  9a  67  fb  4b  b5

Or if you can't run that, no worries, just let me know.

**Comment by agireud** [comment]
Here is the output:
```
0000000 03 d9 a2 9a 67 fb 4b b5
0000010
```

I have also just verified that the current database file is working correctly with the previous version of the app.  My iPad which is still on the previous version reads the database file without issue and importing works as expected.

**Comment by mmcguill** [comment]
Cheers. That's a valid KDBX file alright. I'm running out of ideas for what could be causing the issue here. Would you be willing to uninstall/reinstall the app?

**Comment by agireud** [comment]
Reinstalling did not fix the issue.  I also noticed that the app does not auto sync local files like it used to.  Even when I save the kdbx file into the Strongbox document folder, the safe does not appear in the list automatically.  When I try to open it manually, I get the results I already described to you.

**Comment by mmcguill** [comment]
Ok.

When you say "when I save the kdbx file into the Strongbox document folder", how do you do this?

**Comment by agireud** [comment]
I have tried every method possible like I described previously.  I can list them again.

-  Saving the kdbx file directly to iCloud (any folder) form my desktop then "Adding existing safe -> from Files" from within the app.
- Using a different app on the iPhone to export the kdbx file and using "Save to Files" to save into the On my Iphone -> Strongbox directory.
- Using a different app on the iphone to export the kdbx file using "Copy to Strongbox"

**Comment by mmcguill** [comment]
Ok, thanks. The reason Auto Sync Local Files won't work is because it will only pick up files it thinks are valid. For some reason it doesn't think that file you are using is valid... Will try to work out what is happening here...

**Comment by shad0whawk** [comment]
You asked me about this in my other post so I thought I'd respond in this one. I use KeePass to update my database on my PC.  I don't have any issues opening my database from OneDrive directly or by copying in from the Synqion app.  I do not use a keyfile only a master password.

**Comment by agireud** [comment]
Bumping to get visibility on the edit I made above...The iPad which was confirmed to be working with everything else the same is running version 1.22.1 of Strongbox.

**Comment by mmcguill** [comment]
Cheers, I wonder could you try creating another different new database, and try importing that? What happens? Or if you have Dropbox/Google Drive, try importing from there, does that change anything?

**Comment by agireud** [comment]
I believe my issue has been resolved..

So after creating a new database and not having any issues, I started snooping around further on my phone.  Somehow I had ended up with a corrupt database file cached locally that was not being updated/overwritten.  The rest of my sync clients don't seem to be affected.
 
After removing the locally cached copy manually, the iCloud/Files/Strongbox imports all appear to be working as intended again.  I will update you if I get similar behavior again.

I apologize for the inconvenience but it seems the issue was with file sync client bug, not Strongbox!  Thanks for the quick response and support!

**Comment by mmcguill** [comment]
Aw, super glad to hear it's working ok now. I was starting to run out of ideas! :D 
All the best,
-Mark

**Comment by agireud** [comment]
@mmcguill Will you delete this issue or enable deletion of issues on your repository so that I can?

I understand that you might want to keep a history of issues for other users, but since this was not related to your software in any whatsoever I do not think it provides any value and it is currently impossible for me to remove your repository from my Github account.

**Comment by mmcguill** [comment]
Hi @agireud, apparently I have to move the repository to an "organisation" to allow this... which I'm going to do just now. Hopefully then you can delete your issue... fingers crossed.

**Comment by mmcguill** [comment]
I don't think this works actually, you need to be a member of the organisation :sigh: 

I'll delete this issue for you now...
