### ISSUE TITLE
Modify Existing Connection Credentials to OneDrive, etc.

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#72]
I use OneDrive for Business to host my master database which KeePass syncs with from different PCs.  I've created a connection to it within Strongbox so I can open the latest copy as needed. The problem I encounter is that I have to change my OneDrive password once every 90 days.  At the present, I have to sign out of OneDrive, sign back in, and reestablish my databases.  Is it possible to add functionality that prompts the user for the new password if the authentication fails?  I'm sure this scenario also applies to Google Drive, etc.

**Comment by mmcguill** [comment]
Hi @shad0whawk I think this is OneDrive specific, in that, if I remember correctly the OneDrive API doesn't tell me that the session is expired or authentication has failed. Not 100% sure on this, but I can look into it.

One trick that might be handy is to Disconnect/Remove the OneDrive session from Strongbox by going to Strongbox Settings > Cloud Sessions > Disconnect OneDrive

That should force Strongbox to ask for the Password on the next unlock attempt for a OneDrive database

**Comment by shad0whawk** [comment]
Ok I appreciate it. If I change the password and try to connect, I get an error that authentication failed within Strongbox.  I'll try it again later and test it by disconnecting the OneDrive connection and then try connecting to the existing database.

**Comment by shad0whawk** [comment]
Closing this one
