### ISSUE TITLE
Allow key file from cloud

### ISSUE THREAD

**Issue by huyachao** [mmcguill/Strongbox#73]
My key file is stored in google drive, but Strongbox only support key file from local.
Please add support for key file in cloud, so that I can select key file from google drive.

**Comment by mmcguill** [comment]
Hi @huyachao you can do this already by using the iOS Files app. When you tap a database to unlock it:

1) Select 'Advanced Options'
2) Select 'Password and Key File...'
3) Select 'Files'

from here you can navigate to your Google Drive (you will need to install Google Drive on your iOS Device) and select your key file.

**Comment by huyachao** [comment]
@mmcguill Got it, thank you. The ticket can be closed.

**Comment by SavostinVladimir** [comment]
this doesn't work on macos
