### ISSUE TITLE
Just a Question about Entry History Support in v1.24.0

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#75]
The release notes for 1.24.0 state, “Entry History Support (view, restore, delete, trim).” When I open the database and select an entry, I don’t see any functionality regarding the historical entries. Am I misinterpreting something in the way the release notes are worded and this is a feature not displayed to the user?  Just curious...

**Comment by mmcguill** [comment]
Hi @shad0whawk, there is a little blue button in the top left of the main 'View Entry' screen. Looks like a clock. If you tap that you will be able to view history. If there is no history available the button will not be present. Hope that helps! -Mark

**Comment by shad0whawk** [comment]
Lol wow how did I miss that one???  I found it—thanks for pointing that out. I like that you’ve implemented that feature. It can be very useful at times.
