### ISSUE TITLE
Mac: Favourites/Recently Used Safes (Sidebar or Quick Access on Startup)

### ISSUE THREAD

**Issue by mmcguill** [mmcguill/Strongbox#77]
Provide a quick, convenient way to access recently used or favourite databases at App Startup.

**Comment by georgesnow** [comment]
Persistent side bar that you also hide/reveal would be nice. You got my vote I have work and personal database I use at the same time.

**Comment by mmcguill** [comment]
I believe this is covered now with the Databases Manager. Closing out
