### ISSUE TITLE
Menu bar icon macOS

### ISSUE THREAD

**Issue by milesmcclane** [mmcguill/Strongbox#78]
Would be cool for convenience to have a Menu bar icon for the top bar in macOS, so you can easily access the app when hidden.

**Comment by mmcguill** [comment]
Sounds good

**Comment by mlfreeman2** [comment]
Yeah, this would be a nice timesaver unless MacOS gains a system wide password manager API like iOS

**Comment by mmcguill** [comment]
The MacOS Password Manager API would of course be ideal, but it hasn't released with this years crop of Apple updates (there are some steps in this direction with iPad apps running on Mac)...

**Comment by mlfreeman2** [comment]
Who knows if it’ll ever come to pass though? 

Apple was able to force everyone to use a standard password control on iOS but not on macOS.

**Comment by mmcguill** [comment]
Hi @milesmcclane - This is in place with Mac 1.9.0 - Please close off if happy. Cheers!

**Comment by milesmcclane** [comment]
Great! Thanks
