### ISSUE TITLE
More auto lock options, macOS.

### ISSUE THREAD

**Issue by milesmcclane** [mmcguill/Strongbox#79]
It would be more convenient if there were  more flexible auto lock options. An hour, or longer for example, or even a user defined option. 5 minutes is to short, but I would rather it auto locked incase I forget to lock it when I have finished my session.

**Comment by mmcguill** [comment]
Hi @milesmcclane, these should be in place for you now. No user defined option but some extra choice as a quick fix for now.

**Comment by milesmcclane** [comment]
Great news, thanks!

**Comment by mmcguill** [comment]
No worries!
