### ISSUE TITLE
[Enchancement] autofill search - use fill URL or include sub domain 

### ISSUE THREAD

**Issue by georgesnow** [mmcguill/Strongbox#82]
this is refinement of search when using auto fill. Instead of the default what looks to be the just the domain. 

Example URL: https://www.google.com
Auto fill search result: google

I have about half dozen logins at least with different passwords for internal work sites (no SSO :( for them) similarly I do have some personal ones. It would be nice if it included the sub domain if possible or an option to include it.

Example URL: https://domains.google.com
Auto fill search result: domains.google.com

It greatly narrow down the auto fill results and mind a closer match

**Comment by mmcguill** [comment]
Yes, sounds like a good idea. Thanks @georgesnow

**Comment by mmcguill** [comment]
This should be a bit better/smarter now @georgesnow but with QuickType support you might not need to use it at all, QuickType should suggest matching entries pretty accurately.
