### ISSUE TITLE
Can't save back to WebDAV

### ISSUE THREAD

**Issue by sindastra** [mmcguill/Strongbox#83]
Open WebDAV database, modify title, save, wait for a long time and then suddenly error popup:

`Problem Saving`
`The operation couldn't be completed.`
`(com.MattRajca.DAVkit.error error 423.)`

**Comment by mmcguill** [comment]
Hi @sindastra. that's strange. HTTP 423 indicates a "Locked" status (https://httpstatuses.com/423). Is the database file authorized/available for all HTTP methods on your server?

**Comment by sindastra** [comment]
I'm using Nextcloud with WebDAV and I can read/write using the official Nextcloud client.

For some reason when I tried it again now, I was able to save back to WebDAV using strongbox (although I tried several times a few hours ago without success).

I think I might have to investigate. Any ideas?

**Comment by mmcguill** [comment]
Yes, that is strange indeed. I'm glad it's working for you now, but I'm afraid I'm drawing a blank. Perhaps the file was opened by another application that "locked" it, if that's possible with Nextcloud and WebDAV?

**Comment by sindastra** [comment]
> Perhaps the file was opened by another application that "locked" it, if that's possible with Nextcloud and WebDAV?

I thought the same. My theory was that perhaps KeePassXC is somehow locking the database (as it didn't work on Strongbox while I was having KeePassXC open) but I just tried it again with KeePassXC opened, and Strongbox can read/write the database.

So I don't know why it got locked, but it's still working for me currently.

I would guess this is *solely* a server side issue then and not a Strongbox issue.

**Comment by sindastra** [comment]
Although an idea would be to check for the 423 status, and display a user-friendly message (instead of just letting it timeout to what feels like half a minute of "frozen").

Another/additional idea would be a loading icon so that you know it's actually trying to save.

I'm new to Strongbox and I first thought the app froze, but other than this I think the app is great! 😉

**Comment by mmcguill** [comment]
Thanks @sindastra! Yes, I think the error messaging could be better here, but I think the delay is likely server side too... I'll try improve the messaging!

Best,
-Mark
