### ISSUE TITLE
View Entry Attributes

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#86]
It would be useful to be able to easily see an entry’s attributes such as creation date, modification date, expiration date, and date last accessed when viewing the entry. As it stands, I could find a way to view this information within Strongbox. I can see when the last history item was created but that’s the extent of it.

**Comment by shad0whawk** [comment]
Along that same line, maybe be able to view group attributes as well.

**Comment by mmcguill** [comment]
Yes, good idea, and should be fairly straightforward.

**Comment by shad0whawk** [comment]
And maybe also add the UUID as an attribute we can view—and possibly copy—for each entry (would be helpful for manually creating field references in Strongbox).

**Comment by mmcguill** [comment]
This metadata should be available for you to view now as of 1.27.0 (ID is copyable too)

**Comment by shad0whawk** [comment]
It looks good.  Thank you!  I'm assuming expiration data may show up in the future.

**Comment by mmcguill** [comment]
Yes, this would be connected with #32
