### ISSUE TITLE
Unable to access safe list on iPad in landscape mode

### ISSUE THREAD

**Issue by Ben-Voris** [mmcguill/Strongbox#87]
This happens in quick launch mode. To create it: 

1.  Have multiple safes
1.  Enable quick lunch mode
1.  Put iPad into landscape mode 
1.  Use Safari to access a web page that requires a login
1.  Tap the password prompt 
1.  When presented with the quick launch splash screen, tap cancel to access your other safe

Observe that the “Back to Databases” link is off the screen. 

A workaround is to rotate into portrait mode. Sometimes, after doing this the problem no longer occurs in landscape mode. But, even then, it reoccurs after killing and restarting the password requesting app. 

![IMG_0147](https://user-images.githubusercontent.com/31499002/55036963-d0278e80-4fe1-11e9-9e18-7f65cdb4485d.JPG)

**Comment by mmcguill** [comment]
Hi @Ben-Voris, thanks for the bug report, noted.

**Comment by mmcguill** [comment]
Hi @Ben-Voris - I'm hoping this is fixed for you now in latest version (1.29.3) - but let me know if it isn't or please close if it is. Thanks! -Mark

**Comment by Ben-Voris** [comment]
Yes.  This is resolved in Strongbox 1.29.0.

**Comment by mmcguill** [comment]
Thanks Ben, glad to hear it! All the best, -Mark
