### ISSUE TITLE
Action extension for iOS (esp. Safari)

### ISSUE THREAD

**Issue by vatsanm** [mmcguill/StrongBox#9]
Consider adding/support an action extension similar to the one described in this [StackOverflow](https://stackoverflow.com/questions/38819916/how-to-make-a-compatible-password-extension) discussion so that web logon forms can be filled easily in Safari, Chrome etc. easily.

**Comment by Ben-Voris** [comment]
As I understand them, an action extension would improve security by not putting the password in the clipboard.

**Comment by mmcguill** [comment]
This should be covered now with the addition of the Credentials Provider app extension in iOS12+.
