### ISSUE TITLE
macOS Strongbox - show password in-line like username and double click copy

### ISSUE THREAD

**Issue by georgesnow** [mmcguill/Strongbox#90]
![Screen Shot 2019-04-10 at 9 23 51 AM](https://user-images.githubusercontent.com/12751441/55882675-ed786300-5b72-11e9-823a-5eb1296da44d.png)

screenshot showing the example. keepass on windows offers this functionality makes it bit quicker to grab passwords since its in-line. and it probably be helpful to have a visual indication that the username or password was copied.

**Comment by mmcguill** [comment]
Yes, have something like this planned soon! Thanks @georgesnow

**Comment by mmcguill** [comment]
This is available for you now with 1.7.0
