### ISSUE TITLE
Search enhancement request: non-sequential multi-word AND

### ISSUE THREAD

**Issue by rob3c** [mmcguill/Strongbox#93]
Hi, I just started my trial period recently, and I'm already really happy to have finally found great macos and iOS keepass options! :-)

I noticed there is a difference in how search works across the windows keepass app and Strongbox. I'm used to typing things like `aws vm` and having it return results where those two words appear anywhere in an entry, even if they're not in sequence like a phrase `"aws vm"`.

Is it possible to enhance the search feature so multiple search words are AND-ed together but aren't required to appear sequentially or in order? I haven't been using any clever tagging features, since the full text search behaves this way by default (and my darn muscle memory is on autopilot until I'm wondering why my known entries aren't showing up). I've found that I really like this kind of search option where every word can essentially be a tag.

Thanks in advance!

**Comment by mmcguill** [comment]
Sounds like a great idea, I'll add to list and hopefully get it in shortly...

**Comment by mmcguill** [comment]
Should be working for you now with iOS 1.26.1 and Mac 1.7.0

**Comment by rob3c** [comment]
I tried the new iOS and Mac versions, and they're both working very well! Thanks for being so responsive and updating them so quickly!!!
