### ISSUE TITLE
iOS AutoFill - Add Copy Ability to AutoFill Credential Picker as Fallback

### ISSUE THREAD

**Issue by georgesnow** [mmcguill/Strongbox#94]
So I have discovered some stubborn apps with using password full option. Where password won’t fill properly, which eventually degrades into opening the strongbox app and copy the password and then go back to the app and paste it. Ie this is more other apps not strongbox, but at last it’s a reality. 

Would you consider adding a copy password and maybe username button/option in the autofill extension sheet? That way if the autofill fails you can bring the extension sheet (i think that’s what they are called) back up and just copy your password and paste it.

**Comment by mmcguill** [comment]
Sure, makes sense, should be a quick one.

**Comment by mmcguill** [comment]
Hi @georgesnow, this is available now (long press to copy password/double tap for username) in case the auto fill doesn't fill in the offending form for you. Feel free to re-open if this isn't working as expected.
