### ISSUE TITLE
macOS: Minor UI Improvements

### ISSUE THREAD

**Issue by georgesnow** [mmcguill/Strongbox#96]
Overall I like it a lot better!

-I like I can shrink the window to basically just a list for quick searching and grabbing an entry

-I like the fact I can view  2 entries at once

-the quick copy is AMAZING! and editing in-line on the outline view

Couple things I noticed:

-Search behavior changed - when searching for an item when you press the down arrow or press enter the focus doesn’t move to the results to allow you to move through the results of a search. (you have to hit tab 5 times)

-if you toggle the quick view the size of window changes and when you re-hide the quick view panel the window size remains the new larger size - wonder if maybe it should be more like a “drawer” style. which would be a quick view and/or the editing place for entries? so it would slide and hidden the "main"/(outline view) window would keep its size after hiding it. Having the window bound to main window would also prevent you from having a random entry window left floating about. (also i think it breaks the idea of viewing multiple entries.)
              -along with that having Strongbox remember window size when re-opening?

just thoughts in the first day of using it. Anyway great update!

**Comment by mmcguill** [comment]
Thanks @georgesnow. Yes, I think some of those issues can be tackled/improved. Will leave this ticket open to track.

**Comment by mmcguill** [comment]
Most/All of these are fixed in 1.7.1. Feel free to create separate new issues if something hasn't worked for you
