### ISSUE TITLE
Search UI Results Observation

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#97]
The search result path starts with the database name which seems unnecessary, redundant and takes up space when trying to see the path and folder for the entry. I say unnecessary because the user knows what database they’re in and there’s no cross searching databases at this time. My suggestion would be to trim the database name from the path.  I’d like to easily see where the results are located—specifically the folder. I can turn my phone to landscape mode and easily see the full path, but usually use it in portrait mode so longer paths are condensed. 

If you disagree feel free to close this issue, but i thought I’d at least point it out.

**Comment by mmcguill** [comment]
Yep, makes sense. Will fix.

**Comment by mmcguill** [comment]
Should be fixed as of 1.27.0 - Feel free to reopen if not working as expected.

**Comment by shad0whawk** [comment]
Looks good...thank you!
