### ISSUE TITLE
iOS: Optimize UI Elements Size

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#98]
I love the UI—it’s clean, crisp and easy to follow. My question is around the size of the UI elements. I have an XS Max and the overall UI elements—text and icons—seem large to me. Is it possible to decrease the size of the UI elements to allow for more information on the screen at a smaller size?  I have my system font set to the smallest setting possible. I know that doesn’t impact Strongbox at this time, but wanted to include that as a reference point. It would be nice if it scaled accordingly.

**Comment by mmcguill** [comment]
Yes, I'm hoping to overhaul the UI soon, so should hopefully improve things.

**Comment by mmcguill** [comment]
You should be seeing improvements here with 1.27.0... Let me know what you think...

**Comment by shad0whawk** [comment]
I really like the UI changes you made.  The reduction in text size and spacing look good on my phone.  One thing I noticed is that the History submenu text size and spacing still seem noticeably bigger than the rest of the UI changes almost as if it was overlooked in the overhaul.

**Comment by milesmcclane** [comment]
I haven’t had a proper explore yet but first impressions are that you have massively improved the look of the UI, looks more professional somehow. I know UI should bottom of the list really, in a password safe, but I’m glad you have started the overhaul. 
I’ll have a look through over the next few days to see if I can see any bugs or issues. 
Fantastic!

**Comment by georgesnow** [comment]
love the new interface for iOS! Awesome!

**Comment by mmcguill** [comment]
> I really like the UI changes you made. The reduction in text size and spacing look good on my phone. One thing I noticed is that the History submenu text size and spacing still seem noticeably bigger than the rest of the UI changes almost as if it was overlooked in the overhaul.

Thanks! Do you mean the History Submenu on that Item Details screen, or do you mean the History screen itself?

**Comment by shad0whawk** [comment]
I’m referring to the History submenu that displays a list of historical entries available for viewing. The specific history item looks in line with your latest changes.

**Comment by shad0whawk** [comment]
May have found a new UI glitch as a result of the redesign. It only seems to occur in entries that are “long” by that I mean they contain a lot of text in the notes field plus numerous custom fields combined with the metadata and history elements. In a long entry, if I scroll a towards the bottom and then slide my finger slightly from the left edge, the UI fields appear to reload from the bottom instead of the normal behavior where the previous screen simply slides over from the left. I recorded the screen of you want me to send it to you.

**Comment by shad0whawk** [comment]
I'm sure you're aware of this because all good things take time.  I thought I'd point out that the Autofill module UI is still using the previous larger layout.

**Comment by mmcguill** [comment]
This should be noticeably improved with 1.27.2. Closing out, and feel free to open a new issue if there's something not right in that release.
